// ============================================================================
// FONT CATALOG EXPANSION — +150 fonts premium 2026 (Awwwards + Google + Fontshare)
// ============================================================================
// Adicionado via script para evitar erros de edição manual.
// Categorias: sans, display, serif, mono, script, condensed, variable
// ============================================================================

import type { FontDef } from "./font-catalog";

export const NEW_FONTS_2026: FontDef[] = [
  // ─── SANS — Modern Geometric (15) ───────────────────────────────────────
  { name: "Albert Sans", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Geométrica clean — moderna, SaaS ready" },
  { name: "Anybody", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Display", "Variable"], license: "free", personality: "Variable experimental — letterforms únicas" },
  { name: "Arimo", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Helvetica alternative — clean, neutral" },
  { name: "Atkinson Hyperlegible", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Accessible", "Body"], license: "free", personality: "Otimizada para legibilidade — low vision friendly" },
  { name: "Be Vietnam Pro", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Grotesk vietnamita — clean, multilingual" },
  { name: "Bitter", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Slab-serif humanista — readability" },
  { name: "Carlito", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Calibri alternative — Calibri metric-compatible" },
  { name: "Chivo", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Grotesk argentina — distinctive, warm" },
  { name: "Commissioner", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Variable"], license: "free", personality: "Variable grotesk — flexible, modern" },
  { name: "Domine", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Serif-sans hybrid — readability optimized" },
  { name: "Encode Sans", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "SaaS"], license: "free", personality: "Grotesk condensada — clean, technical" },
  { name: "Epilogue", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Variable"], license: "free", personality: "Variable grotesk — Distillery style" },
  { name: "Familjen Grotesk", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Grotesk escandinava — friendly" },
  { name: "Gudea", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Grotesk técnica — square terminals" },
  { name: "Heebo", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Open Sans alternative — Hebrew + Latin" },

  // ─── SANS — Humanist & Editorial (15) ──────────────────────────────────
  { name: "Hind", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Devanagari + Latin — multilingual" },
  { name: "IBM Plex Sans", source: "IBM, Google", category: "sans", foundry: "IBM", siteType: ["Enterprise", "Tech"], license: "free", personality: "IBM brand — corporativa técnica" },
  { name: "Inconsolata", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Mono humanista — code readability" },
  { name: "Inika", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Display", "Bold"], license: "free", personality: "Serif-sans — fashion, editorial" },
  { name: "Jost", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Futura revival — geométrica clássica" },
  { name: "Kanit", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Thai + Latin — tech display" },
  { name: "Karla", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Body"], license: "free", personality: "Grotesk humanista — warm, friendly" },
  { name: "Khand", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Condensed", "Display"], license: "free", personality: "Condensed — narrow headlines" },
  { name: "Lato", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Humanista clássica — warm, professional" },
  { name: "Mada", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Multilingual"], license: "free", personality: "Arabic + Latin — multilingual" },
  { name: "Mulish", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Muli evolution — rounded, friendly" },
  { name: "Nunito", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Friendly", "UI"], license: "free", personality: "Rounded — soft, approachable" },
  { name: "Nunito Sans", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Nunito sem rounded — clean" },
  { name: "Onest", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["SaaS", "Modern"], license: "free", personality: "Variable modern — Russian design" },
  { name: "Orienta", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Minimal"], license: "free", personality: "Grotesk minimal — clean" },

  // ─── SANS — Tech & Geometric (15) ──────────────────────────────────────
  { name: "Orbitron", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Tech", "Futuristic"], license: "free", personality: "Geométrica futurista — sci-fi, gaming" },
  { name: "PT Sans", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Russian humanista — readability" },
  { name: "Questrial", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Display", "Modern"], license: "free", personality: "Geométrica única — distinctive" },
  { name: "Quicksand", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Friendly", "UI"], license: "free", personality: "Rounded geométrica — soft" },
  { name: "Rajdhani", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Tech", "Condensed"], license: "free", personality: "Condensed tech — gaming, sci-fi" },
  { name: "Rationale", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Tech", "Display"], license: "free", personality: "Geométrica técnica — square" },
  { name: "Roboto", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Standard Android — neutral, ubiquitous" },
  { name: "Roboto Flex", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Variable", "Modern"], license: "free", personality: "Roboto variable — ultra-flexible" },
  { name: "Rubik", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Friendly"], license: "free", personality: "Rounded geométrica — playful" },
  { name: "Saira", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Tech", "Variable"], license: "free", personality: "Grotesk variable — technical" },
  { name: "Saira Condensed", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Condensed", "Display"], license: "free", personality: "Saira condensada — headlines" },
  { name: "Sarabun", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Thai + Latin — multilingual" },
  { name: "Sora", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["Tech", "Display"], license: "free", personality: "Geométrica tech — headings" },
  { name: "Source Sans 3", source: "Google Fonts", category: "sans", foundry: "Adobe", siteType: ["UI", "Body"], license: "free", personality: "Adobe Source — workhorse" },
  { name: "Tajawal", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Multilingual"], license: "free", personality: "Arabic + Latin — modern" },

  // ─── DISPLAY — Bold & Impactful (20) ───────────────────────────────────
  { name: "Teko", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Condensed", "Bold"], license: "free", personality: "Ultra-condensada — impactante" },
  { name: "Tourney", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Variable", "Bold"], license: "free", personality: "Variable display — distinctive" },
  { name: "Work Sans", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Body"], license: "free", personality: "Grotesk workhorse — clean" },
  { name: "Yanone Kaffeesatz", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Condensed", "Display"], license: "free", personality: "Condensada café — distinctive" },
  { name: "Yantramanav", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Multilingual"], license: "free", personality: "Devanagari + Latin — clean" },
  { name: "Zen Kaku Gothic New", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Japanese"], license: "free", personality: "Japanese gothic — modern" },
  { name: "Zen Loop", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Retro"], license: "free", personality: "Loop display — retro unique" },
  { name: "Zen Maru Gothic", source: "Google Fonts", category: "sans", foundry: "Google", siteType: ["UI", "Rounded"], license: "free", personality: "Rounded Japanese — soft" },
  { name: "Zen Old Mincho", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Japanese"], license: "free", personality: "Japanese mincho — traditional" },
  { name: "Zen Tokyo Zoo", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Bold"], license: "free", personality: "Tokyo display — ultra-bold" },
  { name: "Anton", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Poster"], license: "free", personality: "Black condensed — poster impact" },
  { name: "Archivo Black", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Display"], license: "free", personality: "Archivo black — heavy display" },
  { name: "Alfa Slab One", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Slab", "Bold"], license: "free", personality: "Slab-serif ultra-bold — poster" },
  { name: "Bungee", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Urban"], license: "free", personality: "Urban display — streetwear" },
  { name: "Bungee Inline", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Display"], license: "free", personality: "Bungee inline — outlined" },
  { name: "Bungee Shade", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Display"], license: "free", personality: "Bungee shade — 3D effect" },
  { name: "Codystar", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Dot"], license: "free", personality: "Dot matrix display — retro tech" },
  { name: "Dela Gothic One", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Japanese"], license: "free", personality: "Japanese gothic ultra-bold" },
  { name: "DotGothic16", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Retro"], license: "free", personality: "Pixel dot — retro gaming" },
  { name: "Goldman", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Tech display — angular" },

  // ─── DISPLAY — Creative & Experimental (20) ────────────────────────────
  { name: "Grenze", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Variable"], license: "free", personality: "Variable display — German style" },
  { name: "Grenze Gotisch", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Blackletter"], license: "free", personality: "Gotisch — blackletter modern" },
  { name: "Holtwood One SC", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Slab"], license: "free", personality: "Slab small-caps — poster" },
  { name: "Iceberg", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Ice display — angular cold" },
  { name: "Iceland", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Tech display — geometric" },
  { name: "Jacques Francois", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Classic"], license: "free", personality: "French classic — elegant" },
  { name: "Jacques Francois Shadow", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Shadow"], license: "free", personality: "French classic shadow — 3D" },
  { name: "Kavoon", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Bold"], license: "free", personality: "Bold display — playful" },
  { name: "Kdam Thmor", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Khmer + Latin — tech" },
  { name: "Keania One", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Bold"], license: "free", personality: "Bold display — industrial" },
  { name: "Kreon", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Slab-serif — readability" },
  { name: "Kristi", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Handwritten"], license: "free", personality: "Handwritten — calligraphy" },
  { name: "La Belle Aurore", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Cursive"], license: "free", personality: "Cursive — elegant script" },
  { name: "Lakki Reddy", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Handwritten"], license: "free", personality: "Telugu handwritten — playful" },
  { name: "Langar", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Multilingual"], license: "free", personality: "Gurmukhi + Latin — display" },
  { name: "Lemon", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Retro"], license: "free", personality: "Retro display — 70s vibe" },
  { name: "Lemonada", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Display", "Friendly"], license: "free", personality: "Arabic + Latin — friendly" },
  { name: "Lilita One", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Bold", "Display"], license: "free", personality: "Bold display — poster" },
  { name: "Lobster", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Bold"], license: "free", personality: "Script bold — distinctive" },
  { name: "Lobster Two", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Display"], license: "free", personality: "Lobster refined — elegant" },

  // ─── SERIF — Editorial & Elegant (20) ──────────────────────────────────
  { name: "Playfair Display", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Fashion"], license: "free", personality: "Alto-contraste — luxury/fashion" },
  { name: "Cormorant Garamond", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Elegant"], license: "free", personality: "Ultra-fina elegante — delicada" },
  { name: "EB Garamond", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Garamond clássica — readability" },
  { name: "Spectral", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Serif moderna — screen-optimized" },
  { name: "Spectral SC", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Display"], license: "free", personality: "Spectral small-caps — elegant" },
  { name: "Crimson Text", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Serif readability — book-style" },
  { name: "Crimson Pro", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Crimson evolution — modern" },
  { name: "Source Serif 4", source: "Google Fonts", category: "serif", foundry: "Adobe", siteType: ["Editorial", "Body"], license: "free", personality: "Adobe Source Serif — workhorse" },
  { name: "Source Serif Pro", source: "Google Fonts", category: "serif", foundry: "Adobe", siteType: ["Editorial", "Body"], license: "free", personality: "Source Serif original" },
  { name: "Cormorant", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "Cormorant display — dramatic" },
  { name: "Cormorant Infant", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Body"], license: "free", personality: "Cormorant infant — readable" },
  { name: "Cormorant SC", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "Cormorant small-caps" },
  { name: "Cormorant Unicase", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "Cormorant unicase — unique" },
  { name: "Cormorant Upright", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "Cormorant upright — elegant" },
  { name: "DM Serif Display", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "DM Serif display — dramatic" },
  { name: "DM Serif Text", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "DM Serif text — readable" },
  { name: "Enriqueta", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Slab-serif humanista" },
  { name: "Frank Ruhl Libre", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Hebrew"], license: "free", personality: "Hebrew + Latin — classic" },
  { name: "Glegoo", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Slab-serif — readability" },
  { name: "Hepta Slab", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Slab", "Variable"], license: "free", personality: "Variable slab — flexible" },

  // ─── SERIF — Modern & Editorial (15) ───────────────────────────────────
  { name: "IBM Plex Serif", source: "IBM, Google", category: "serif", foundry: "IBM", siteType: ["Enterprise", "Body"], license: "free", personality: "IBM brand serif — corporate" },
  { name: "Inria Serif", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Modern"], license: "free", personality: "Serif moderna — French tech" },
  { name: "Lora", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Caligráfica brushed — warm" },
  { name: "Markazi Text", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Arabic"], license: "free", personality: "Arabic + Latin — readable" },
  { name: "Mate", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Serif clássica — book style" },
  { name: "Mate SC", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Display"], license: "free", personality: "Mate small-caps" },
  { name: "Merriweather", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Serif readability — screen-optimized" },
  { name: "Noto Serif", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Multilingual"], license: "free", personality: "Universal serif — multilingual" },
  { name: "Noto Serif Display", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Display", "Multilingual"], license: "free", personality: "Noto display — dramatic" },
  { name: "Noto Serif SC", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Chinese"], license: "free", personality: "Chinese serif — multilingual" },
  { name: "Old Standard TT", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Classic"], license: "free", personality: "Classic standard — book" },
  { name: "PT Serif", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Body"], license: "free", personality: "Russian serif — readable" },
  { name: "Philosopher", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Display", "Modern"], license: "free", personality: "Serif moderna — distinctive" },
  { name: "Pridi", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Editorial", "Thai"], license: "free", personality: "Thai + Latin — readable" },
  { name: "Prata", source: "Google Fonts", category: "serif", foundry: "Google", siteType: ["Luxury", "Display"], license: "free", personality: "Serif elegante — fashion" },

  // ─── MONO — Code & Technical (15) ──────────────────────────────────────
  { name: "JetBrains Mono", source: "JetBrains, Google", category: "mono", foundry: "JetBrains", siteType: ["Dev", "Code"], license: "free", personality: "Code-optimized — ligatures" },
  { name: "Fira Code", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Ligatures — code poetry" },
  { name: "Source Code Pro", source: "Google Fonts", category: "mono", foundry: "Adobe", siteType: ["Dev", "Code"], license: "free", personality: "Adobe Source Mono — workhorse" },
  { name: "IBM Plex Mono", source: "IBM, Google", category: "mono", foundry: "IBM", siteType: ["Enterprise", "Code"], license: "free", personality: "IBM brand mono — corporate" },
  { name: "Roboto Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Roboto family — clean" },
  { name: "Ubuntu Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Ubuntu brand — distinctive" },
  { name: "Inconsolata", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Humanista — readability" },
  { name: "Space Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Tech", "Awwwards"], license: "free", personality: "Retro-futurista — distinctive" },
  { name: "Major Mono Display", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Display", "Tech"], license: "free", personality: "Mono display — bold tech" },
  { name: "Cousine", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Code"], license: "free", personality: "Courier alternative — classic" },
  { name: "Cutive Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Editorial", "Classic"], license: "free", personality: "Typewriter — vintage" },
  { name: "DM Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Modern"], license: "free", personality: "DM family — clean modern" },
  { name: "DotGothic16", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Retro", "Gaming"], license: "free", personality: "Pixel dot — retro gaming" },
  { name: "Nanum Gothic Coding", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Korean"], license: "free", personality: "Korean + Latin code" },
  { name: "Spline Sans Mono", source: "Google Fonts", category: "mono", foundry: "Google", siteType: ["Dev", "Variable"], license: "free", personality: "Variable mono — flexible" },

  // ─── SCRIPT — Handwritten & Calligraphy (15) ───────────────────────────
  { name: "Dancing Script", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Friendly"], license: "free", personality: "Script brushed — friendly" },
  { name: "Pacifico", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Bold"], license: "free", personality: "Script bold — surf/retro" },
  { name: "Caveat", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Handwritten"], license: "free", personality: "Handwritten — casual" },
  { name: "Caveat Brush", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Brush"], license: "free", personality: "Brush script — dynamic" },
  { name: "Sacramento", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Elegant"], license: "free", personality: "Mono-line script — elegant" },
  { name: "Allura", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Luxury"], license: "free", personality: "Formal script — wedding" },
  { name: "Alex Brush", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Brush"], license: "free", personality: "Brush elegant — fashion" },
  { name: "Arizonia", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Wild"], license: "free", personality: "Wild west — distinctive" },
  { name: "Bad Script", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Casual"], license: "free", personality: "Imperfect — handwritten casual" },
  { name: "Bilbo Swash Caps", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Swash"], license: "free", personality: "Swash caps — elegant" },
  { name: "Cookie", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Brush"], license: "free", personality: "Brush script — vintage" },
  { name: "Great Vibes", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Wedding"], license: "free", personality: "Formal wedding — elegant" },
  { name: "Italianno", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Calligraphy"], license: "free", personality: "Italian calligraphy — flowing" },
  { name: "Marck Script", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "Handwritten"], license: "free", personality: "Handwritten — personal" },
  { name: "Parisienne", source: "Google Fonts", category: "display", foundry: "Google", siteType: ["Script", "French"], license: "free", personality: "French script — romantic" },

  // ─── Fontshare Premium (10) ────────────────────────────────────────────
  { name: "Telma", source: "Fontshare, Awwwards", category: "display", foundry: "Fontshare", siteType: ["Awwwards", "Display"], license: "free", personality: "Display geometric — Awwwards SOTD" },
  { name: "Boska", source: "Fontshare, Awwwards", category: "display", foundry: "Fontshare", siteType: ["Awwwards", "Display"], license: "free", personality: "Wedge-serif hybrid — distinctive" },
  { name: "Wargaming", source: "Fontshare, gaming", category: "display", foundry: "Fontshare", siteType: ["Gaming", "Bold"], license: "free", personality: "Gaming display — angular bold" },
  { name: "Strike", source: "Fontshare, tech", category: "display", foundry: "Fontshare", siteType: ["Tech", "Display"], license: "free", personality: "Tech display — strike-through" },
  { name: "Migra", source: "Fontshare, editorial", category: "serif", foundry: "Fontshare", siteType: ["Editorial", "Magazine"], license: "free", personality: "Serif editorial — magazine" },
  { name: "Panch", source: "Fontshare, Awwwards", category: "sans", foundry: "Fontshare", siteType: ["Awwwards", "Modern"], license: "free", personality: "Sans moderna — Awwwards" },
  { name: "Rocher", source: "Fontshare, display", category: "display", foundry: "Fontshare", siteType: ["Display", "Bold"], license: "free", personality: "Display bold — chunky" },
  { name: "Penaflor", source: "Fontshare, editorial", category: "serif", foundry: "Fontshare", siteType: ["Editorial", "Luxury"], license: "free", personality: "Serif luxury — fashion" },
  { name: "Sahitya", source: "Fontshare, editorial", category: "serif", foundry: "Fontshare", siteType: ["Editorial", "Body"], license: "free", personality: "Serif readability — book" },
  { name: "Triode", source: "Fontshare, tech", category: "mono", foundry: "Fontshare", siteType: ["Tech", "Mono"], license: "free", personality: "Mono tech — distinctive" },
];
