// ============================================================================
// SCRAPED FONTS — Fonts extraídas de sites curados (free for commercial use)
// ============================================================================
// Fontes: BeFonts, Fontesk, FreeFaces, UseModify (Nov 2026 scrape)
// Todas free for commercial use. Organizadas por site de origem.
// ============================================================================

import type { FontDef } from "./font-catalog";

export const SCRAPED_FONTS: FontDef[] = [
  // ─── BeFonts (https://befonts.com) — 128 fonts ──────────
  { name: "Amazing Sweety", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Ancestri Slab", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Apoca Playful", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Awanika Display", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "BF Material", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "BF Required Realities", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Bai Jamjuree Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Balhattan", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Barcelona 2026", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Beautiful Reluxes", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Behance", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Biarty Sans", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Big Over", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Blackcraft Display", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Board Of Directors", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Boldone Display", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Boudica Perfect", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Browse", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Bukittinggi", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Chainsaw Carnage", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Chela One", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Collections", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "College Vista 34", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Courbe Sans", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Crayon Libre", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Crimson Story", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Cutes Bright", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Darkbyte", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Dekko Extra Bold", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Dekko Regular", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Delta Block", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Designers", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Dmca", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Drybrush", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Editonials", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Facebook", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Falaro", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Fluctuation Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Font Collections", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Font Designers", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Fonts", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Free Cheese", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "From The Stars", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Gameness Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Ghivane", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Gocake", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Goodlooking", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Gotfridus Blackletter", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Graphic Design", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Grimfay", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Halloween Harry G7", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Heellaaz", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Helvetica Neue LT Pro Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Helvetica Neue LT Std", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Honestlife", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Imferture Roasted", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Jogrunge", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Juliet Honey", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Juturu Geometric Variable", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Kyivtype Serif Font Family", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Kyivtype Titling Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Kyivtype Variable", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Lazover Classico Decorative Typeface", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Madawaska", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Malebo", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Mecha Core Futuristic Gaming", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Moments Stories", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "More Awesome Similar Free Fonts", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Myako", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "New Message", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "North Kids", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Operation Napalm", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Origin Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Oserif", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Pixelated Elegance", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Pixelbasel", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Pixelzone", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Porto Buena", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Qubic Grid", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Racepack Circuit", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Ragman", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Raveling Melany", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Rd Party Ad Content", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Refuel", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Report Message", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Retrochips", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Reversal Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Rhythme Captured", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Rijusans", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Robout", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Romestone", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Rosetaen Serif", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Ruthless Sketch", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "SFC Bronkos", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "SFC Slemans", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "SFC Wezards", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Segmented Display", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Share On Pinterest", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Sign In", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Simply Addiction", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Skip To Content", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Skyte Display", source: "BeFonts", category: "display", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Slangtury Bohemis", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Storiesky", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Stranger Friz", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Submission", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Submit", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Subway Berlin Street Graffiti", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Super Pandora", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Sweet Allgore", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "The Villas Luxury Display Serif", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Through Out", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Tink Real", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "UKIJ Mejnuntal", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Ultraproxi Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Unlimited", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Varsity Impact", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Vectipede Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Vehicle Licensing &amp; Registration", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Veloura Serif", source: "BeFonts", category: "serif", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Velvetoon Lava Groovy Retro", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Visual Art &amp; Design", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Vyaz Pixel", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "World Cup", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Writers Resources", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Zerbydoo", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },
  { name: "Zingende Font Family", source: "BeFonts", category: "sans", foundry: "BeFonts", siteType: ["Scraped"], license: "free", personality: "Extraída de BeFonts" },

  // ─── Fontesk (https://fontesk.com) — 22 fonts ──────────
  { name: "Asal_usul", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Bang_pop", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Cantas_de_abril", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Capo_sfogliato", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Chomage", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Courbe_sans", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Eastern_rodopes", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Gatchina", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Greengoth", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Lazy_arie", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Malam_poek", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Mephisto", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Rahull", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Romano_revival", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Storymaster", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_bugly", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_hockey", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_kidpop", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_nugget", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_starfish", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Super_warming", source: "Fontesk", category: "sans", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },
  { name: "Youth_shandey", source: "Fontesk", category: "display", foundry: "Fontesk", siteType: ["Scraped"], license: "free", personality: "Extraída de Fontesk" },

  // ─── FreeFaces (https://freefaces.gallery) — 10 fonts ──────────
  { name: "Barriecito", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Façade", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "GTL001", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Getai Grotesk", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Hyperlegible Sans", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Lastik", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Lost In Space", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Martian Mono", source: "FreeFaces", category: "mono", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Memoir", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },
  { name: "Unique", source: "FreeFaces", category: "sans", foundry: "FreeFaces", siteType: ["Scraped"], license: "free", personality: "Extraída de FreeFaces" },

  // ─── UseModify (https://usemodify.com) — 168 fonts ──────────
  { name: "A MONO", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "ADAXI", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "APL333", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "APL386", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "AUTHENTIC Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Aboensis", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Aileron", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Alef", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Alte DIN 1451", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ancial", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Anka/coder", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Anonymous Pro", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Aquis", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ark", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Astloch", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Autopia", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Avara", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Bagnard", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Banquise", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Barlow", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Bluu", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Borel", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Boris", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Breite", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "C Reduci", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "CATV 6X12 9", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "CMRDD", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "CP Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Caladea", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Canola", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Centaury", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Charis SIL", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Chicagoflf", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Clear Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Coaster Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Comic Sans MS", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Computer Modern", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Cotham Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "DOF", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Dauphine", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Dejavu", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Diamondgrotesk", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Didot", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Dinish", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ductus", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Elvenes", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Fantasque Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ferrite Core", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Fibel", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Fifteentwenty", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Fivo Sans Modern", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Flexi IBM VGA", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Fontlab", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Frames Part One", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Free Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Galgo Condensed", source: "UseModify", category: "display", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Gap Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Garamon(d/t", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Garcia", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Gidole", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Glacier", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Goozette", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Grammatika Regular", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "HK Grotesk", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Hack", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Half", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Hanken", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Heal The Web", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Herbiflora", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Hibana", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Honoka Mincho", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ia Writer", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Indira K", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Inknut Antiqua", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Inria", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Interval", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Iosevka", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Isobare", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "JRUG PUNK", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Jet Brains Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Jgs", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Junicode", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Karmilla", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Karrik", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Kikuta", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Lab Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "League Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Liberation", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Lil Grotesk", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Limousine", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Linux Libertine", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Lucette", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Luculent", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Lunchtype", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Manusquared", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Maplemono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Metaaccanthis", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Meyrin CERN Terminal", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Moche", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Monoid", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Monomusic", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Nanook", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "National Park Typeface", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Necto Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Nighthawk", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Not Comic", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Not Courier Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Now Alt", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Orbit", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Orchard Linear", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Overpass", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "PT Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Panamera", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Panchi Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Pecita", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Pressuru", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Pro", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Propcourier Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ptah", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Punk Nova", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Québec", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Railway Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ranchers", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Recursive", source: "UseModify", category: "display", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Redaction", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Roadiz Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Routed Gothic", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Rumeur", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Sani Trixie Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Savate", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Selectric", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Server Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Sinkin Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Snap", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Sometype Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Sono", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Source Sans Pro", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Space Notorious", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Sprat", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Steps Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Struggle", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "TGL", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Techna Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Terminal Grotesque", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Terminus TTF", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Times New Roman", source: "UseModify", category: "serif", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Toren", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Tribalium Neue", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Tuffy", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Ume Fonts", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Unifraktur", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Verily Serif Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Version", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Victor Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Violet Sans", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Vollkorn", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Vägra", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "W Droge", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Wavy", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Westernic", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Whois Mono", source: "UseModify", category: "mono", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Wondertype", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Work Avec", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Xa000", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Xolonium", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Xxqueen", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Young Serif", source: "UseModify", category: "serif", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },
  { name: "Écrou", source: "UseModify", category: "sans", foundry: "UseModify", siteType: ["Scraped"], license: "free", personality: "Extraída de UseModify" },

];

// Total: 328 fonts extraídas de 5 sites