// ============================================================================
// skills-catalog.ts — Catálogo de skills + integrações com modos de seleção
// ============================================================================
// SKILL: STEM Calculative Problem-Solving + Visual Exploration
// Cada skill tem: id, nome, categoria, descrição, quando usar, exemplo real
// Modos: Recomendada (auto), Alternativa, Opcional, Manual (escolho eu)
// ============================================================================

export type SkillMode = "recomendada" | "alternativa" | "opcional" | "manual" | "off";

export interface Skill {
  id: string;
  nome: string;
  categoria: "UI" | "Animações" | "MCP" | "Backend" | "IA" | "DevOps" | "Design";
  icone: string;
  descricao: string;
  quandoUsar: string;
  exemplo: string;
  url?: string;
  // Modo recomendado por defeito (baseado no nicho)
  modoDefault: SkillMode;
}

// ============================================================================
// SKILLS — catálogo completo (reais, sem inventar)
// ============================================================================
export const SKILLS_CATALOG: Skill[] = [
  // ── UI Base ──
  {
    id: "shadcn-ui",
    nome: "shadcn/ui",
    categoria: "UI",
    icone: "Component",
    descricao: "Component library baseada em Radix UI + Tailwind. Copy-paste, não npm install.",
    quandoUsar: "SEMPRE. É a foundation de qualquer projeto Next.js moderno.",
    exemplo: "Vercel, Linear, Resend, Cal.com — todos usam shadcn/ui.",
    url: "https://ui.shadcn.com",
    modoDefault: "recomendada",
  },
  {
    id: "radix-ui",
    nome: "Radix UI",
    categoria: "UI",
    icone: "Component",
    descricao: "Primitives headless acessíveis (dialogs, dropdowns, popovers). Acessibilidade WCAG.",
    quandoUsar: "Sempre que precisas de componentes interativos acessíveis.",
    exemplo: "shadcn/ui é built on top of Radix. Linear, Vercel usam Radix diretamente.",
    url: "https://radix-ui.com",
    modoDefault: "recomendada",
  },
  {
    id: "tailwind-4",
    nome: "Tailwind CSS 4",
    categoria: "UI",
    icone: "Palette",
    descricao: "CSS framework utility-first. V4 com @theme inline, CSS-first config, Oxide engine.",
    quandoUsar: "SEMPRE. É o standard da indústria para styling.",
    exemplo: "Vercel, Linear, Stripe, GitHub — todos usam Tailwind.",
    url: "https://tailwindcss.com",
    modoDefault: "recomendada",
  },
  {
    id: "next-themes",
    nome: "next-themes",
    categoria: "UI",
    icone: "Moon",
    descricao: "Dark/light mode para Next.js. SSR-safe, sem flash, persistente.",
    quandoUsar: "Sempre que precisas de dark mode (praticamente sempre).",
    exemplo: "Vercel, Linear, shadcn/ui docs — todos usam next-themes.",
    url: "https://github.com/pacocoursey/next-themes",
    modoDefault: "recomendada",
  },
  {
    id: "cmdk",
    nome: "cmdk",
    categoria: "UI",
    icone: "Command",
    descricao: "Command palette (Cmd+K). Busca fuzzy, keyboard navigation.",
    quandoUsar: "Em apps com mais de 5 páginas. Essencial para produtividade.",
    exemplo: "Vercel, Linear, Raycast, GitHub — todos têm Cmd+K.",
    url: "https://cmdk.paco.me",
    modoDefault: "alternativa",
  },
  {
    id: "sonner",
    nome: "sonner",
    categoria: "UI",
    icone: "Bell",
    descricao: "Toasts modernos com animações spring. Substitui radix-toast.",
    quandoUsar: "Sempre que precisas de notificações (toasts).",
    exemplo: "Vercel, Linear, shadcn/ui — todos migraram para sonner.",
    url: "https://sonner.emilkowal.ski",
    modoDefault: "recomendada",
  },

  // ── Animações ──
  {
    id: "motion",
    nome: "Motion (Framer Motion)",
    categoria: "Animações",
    icone: "Zap",
    descricao: "Biblioteca de animações para React. useScroll, useTransform, layout animations, springs.",
    quandoUsar: "SEMPRE. É o standard para animações em React/Next.js.",
    exemplo: "Vercel, Linear, Framer, Stripe — todos usam Motion.",
    url: "https://motion.dev",
    modoDefault: "recomendada",
  },
  {
    id: "lenis",
    nome: "Lenis",
    categoria: "Animações",
    icone: "MousePointerClick",
    descricao: "Smooth scroll leve. Substitui Locomotive Scroll. Hook useLenis.",
    quandoUsar: "Em sites premium com scroll (landing pages, portfolios, agências).",
    exemplo: "Awwwards SOTD, Framer, Apple product pages.",
    url: "https://lenis.studiofreight.com",
    modoDefault: "alternativa",
  },
  {
    id: "gsap",
    nome: "GSAP ScrollTrigger",
    categoria: "Animações",
    icone: "Film",
    descricao: "GreenSock Animation Platform. ScrollTrigger para animações complexas ao scroll.",
    quandoUsar: "Para animações avançadas (horizontal scroll, pin sections, timelines).",
    exemplo: "Awwwards sites, Apple product pages, Nike stories.",
    url: "https://gsap.com",
    modoDefault: "opcional",
  },
  {
    id: "rive",
    nome: "Rive",
    categoria: "Animações",
    icone: "Sparkles",
    descricao: "Animações vetoriais interativas com states e inputs. Pequenas e com personalidade.",
    quandoUsar: "Para micro-interactions orgânicas (loading, onboarding, empty states).",
    exemplo: "Mailchimp, Slack onboarding, Cash App.",
    url: "https://rive.app",
    modoDefault: "opcional",
  },
  {
    id: "lottie",
    nome: "Lottie (lottie-react)",
    categoria: "Animações",
    icone: "Sparkles",
    descricao: "Animações After Effects exportadas como JSON. Leves e escaláveis.",
    quandoUsar: "Alternativa ao Rive para animações já feitas em After Effects.",
    exemplo: "Airbnb, Slack, Dropbox, Google.",
    url: "https://lottiefiles.com",
    modoDefault: "opcional",
  },
  {
    id: "react-three-fiber",
    nome: "React Three Fiber",
    categoria: "Animações",
    icone: "Box",
    descricao: "Three.js para React. 3D scenes, partículas, modelos interativos.",
    quandoUsar: "Para 3D/WebGL (produtos físicos, configuradores, backgrounds vivos).",
    exemplo: "Apple Vision Pro, Nike By You, Awwwards 3D sites.",
    url: "https://docs.pmnd.rs/react-three-fiber",
    modoDefault: "opcional",
  },

  // ── MCP (Model Context Protocol) ──
  {
    id: "figma-mcp",
    nome: "Figma MCP Server",
    categoria: "MCP",
    icone: "Figma",
    descricao: "Handoff de design tokens e componentes Figma → código. Dev Mode, code connect.",
    quandoUsar: "SEMPRE quando há designer na equipa. Essencial para Figma → Next.js.",
    exemplo: "Vercel, Linear, Resend — todos usam Figma MCP para handoff.",
    url: "https://github.com/GLips/Figma-Context-MCP",
    modoDefault: "recomendada",
  },
  {
    id: "context7-mcp",
    nome: "Context7 MCP",
    categoria: "MCP",
    icone: "BookOpen",
    descricao: "Documentação atualizada de libs diretamente no LLM. Substitui knowledge cutoff.",
    quandoUsar: "SEMPRE. Garante que o GLM-5.2 usa a versão mais recente das libs.",
    exemplo: "Recomendado por Cursor, Claude Code, Windsurf.",
    url: "https://context7.com",
    modoDefault: "recomendada",
  },
  {
    id: "browser-tools-mcp",
    nome: "Browser Tools MCP",
    categoria: "MCP",
    icone: "Globe",
    descricao: "QA visual, debugging CSS, performance audit, Lighthouse. Inspeciona em runtime.",
    quandoUsar: "Para QA visual e debugging de CSS/accessibility.",
    exemplo: "Agências e equipas que fazem QA visual rigoroso.",
    url: "https://github.com/AgentDeskAI/browser-tools-mcp",
    modoDefault: "alternativa",
  },
  {
    id: "github-mcp",
    nome: "GitHub MCP",
    categoria: "MCP",
    icone: "Github",
    descricao: "Versionamento, PRs, code review automatizado, issues. Tudo via MCP.",
    quandoUsar: "SEMPRE. Git é essencial em qualquer projeto.",
    exemplo: "Qualquer equipa que usa GitHub.",
    url: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    modoDefault: "recomendada",
  },
  {
    id: "filesystem-mcp",
    nome: "Filesystem MCP",
    categoria: "MCP",
    icone: "Folder",
    descricao: "Acesso a ficheiros locais para scaffolding e gestão de assets.",
    quandoUsar: "Para fluxos com assets locais ou geração de múltiplos ficheiros.",
    exemplo: "Claude Code, Cursor com scaffolding.",
    url: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    modoDefault: "opcional",
  },
  {
    id: "sequential-thinking-mcp",
    nome: "Sequential Thinking MCP",
    categoria: "MCP",
    icone: "Brain",
    descricao: "Multi-step reasoning para specs complexas. Quebra problemas em passos.",
    quandoUsar: "Para specs/arquitetura complexa que requer raciocínio step-by-step.",
    exemplo: "Modelscope, Anthropic recomenda para chain-of-thought.",
    url: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    modoDefault: "opcional",
  },
  {
    id: "magic-mcp",
    nome: "Magic MCP (21st.dev)",
    categoria: "MCP",
    icone: "Wand2",
    descricao: "Gera componentes UI premium sob demanda. Awwwards-quality components.",
    quandoUsar: "Para componentes complexos que demoram muito a construir à mão.",
    exemplo: "21st.dev community, usado por agências premium.",
    url: "https://21st.dev",
    modoDefault: "opcional",
  },
  {
    id: "puppeteer-mcp",
    nome: "Puppeteer MCP",
    categoria: "MCP",
    icone: "Globe",
    descricao: "E2E testing e scraping via Puppeteer. Alternativa ao Browser Tools.",
    quandoUsar: "Para E2E tests automatizados e screenshots.",
    exemplo: "Equipas que usam Puppeteer para CI/CD.",
    url: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    modoDefault: "opcional",
  },

  // ── Backend ──
  {
    id: "prisma",
    nome: "Prisma ORM",
    categoria: "Backend",
    icone: "Database",
    descricao: "ORM type-safe para PostgreSQL/MySQL/SQLite. Migrations, studio, introspection.",
    quandoUsar: "Sempre que precisas de base de dados. Standard para Next.js.",
    exemplo: "Cal.com, Vercel, Linear — todos usam Prisma.",
    url: "https://prisma.io",
    modoDefault: "recomendada",
  },
  {
    id: "supabase",
    nome: "Supabase",
    categoria: "Backend",
    icone: "Database",
    descricao: "Backend-as-a-service. Postgres + Auth + Storage + Realtime + Edge Functions.",
    quandoUsar: "Para MVPs rápidos ou quando precisas de Auth + DB sem configuração.",
    exemplo: "1Calendar, Markprompt, Mintlify — usam Supabase.",
    url: "https://supabase.com",
    modoDefault: "alternativa",
  },
  {
    id: "nextauth",
    nome: "Auth.js (NextAuth v5)",
    categoria: "Backend",
    icone: "Lock",
    descricao: "Autenticação para Next.js. OAuth, magic links, credentials, JWT, sessions.",
    quandoUsar: "Sempre que precisas de login/registro. Standard para Next.js.",
    exemplo: "Cal.com, Vercel dashboard, shadcn/ui admin.",
    url: "https://authjs.dev",
    modoDefault: "recomendada",
  },
  {
    id: "upstash",
    nome: "Upstash Redis",
    categoria: "Backend",
    icone: "Database",
    descricao: "Redis serverless para caching, rate limiting, queues. Pay-per-request.",
    quandoUsar: "Para caching, rate limiting, ou pub/sub em serverless.",
    exemplo: "Vercel, Next.js apps que precisam de cache edge.",
    url: "https://upstash.com",
    modoDefault: "opcional",
  },
  {
    id: "neon",
    nome: "Neon Postgres",
    categoria: "Backend",
    icone: "Database",
    descricao: "Postgres serverless com branching. Escala para zero. Free tier generoso.",
    quandoUsar: "Alternativa ao Supabase para só DB (sem Auth/Storage).",
    exemplo: "Replit, Vercel recommend Neon.",
    url: "https://neon.tech",
    modoDefault: "alternativa",
  },

  // ── IA ──
  {
    id: "vercel-ai-sdk",
    nome: "Vercel AI SDK",
    categoria: "IA",
    icone: "Brain",
    descricao: "SDK para streaming de LLMs, tool calling, RAG. Multi-provider (OpenAI, Anthropic, Google).",
    quandoUsar: "Sempre que o site tem features de IA (chatbot, recomendações, geração).",
    exemplo: "Vercel AI Chat, ChatGPT clones, Perplexity-like apps.",
    url: "https://sdk.vercel.ai",
    modoDefault: "recomendada",
  },
  {
    id: "openai",
    nome: "OpenAI API",
    categoria: "IA",
    icone: "Brain",
    descricao: "GPT-4o, GPT-4-vision, DALL-E, Whisper, TTS. Para chatbots, geração de conteúdo.",
    quandoUsar: "Para features de IA quando não usas Vercel AI SDK diretamente.",
    exemplo: "Quase todo SaaS com IA usa OpenAI.",
    url: "https://platform.openai.com",
    modoDefault: "alternativa",
  },
  {
    id: "anthropic",
    nome: "Anthropic Claude API",
    categoria: "IA",
    icone: "Brain",
    descricao: "Claude 3.5 Sonnet, Opus, Haiku. Para reasoning complexo, código longo, analysis.",
    quandoUsar: "Para tarefas que exigem mais reasoning que GPT-4o.",
    exemplo: "Cursor, Replit, Notion AI usam Claude.",
    url: "https://anthropic.com",
    modoDefault: "opcional",
  },
  {
    id: "glm",
    nome: "GLM-5.2 (Z.ai)",
    categoria: "IA",
    icone: "Brain",
    descricao: "Modelo GLM-5.2 via Z.ai. Function calling nativo, structured output, multimodal.",
    quandoUsar: "Para features de IA quando queres custo-benefício com quality.",
    exemplo: "Inaugura-Base usa GLM-5.2 para geração de specs.",
    url: "https://z.ai",
    modoDefault: "recomendada",
  },

  // ── DevOps ──
  {
    id: "vercel",
    nome: "Vercel",
    categoria: "DevOps",
    icone: "Triangle",
    descricao: "Deploy Next.js com 1 click. Edge functions, preview deployments, analytics.",
    quandoUsar: "SEMPRE para Next.js. É o host nativo.",
    exemplo: "Vercel, Linear, Cal.com, Resend — todos hosted na Vercel.",
    url: "https://vercel.com",
    modoDefault: "recomendada",
  },
  {
    id: "sentry",
    nome: "Sentry",
    categoria: "DevOps",
    icone: "AlertCircle",
    descricao: "Error tracking em tempo real. Stack traces, performance monitoring, session replay.",
    quandoUsar: "Production. Essencial para monitorar erros em produção.",
    exemplo: "Vercel, Linear, Discord — todos usam Sentry.",
    url: "https://sentry.io",
    modoDefault: "recomendada",
  },
  {
    id: "posthog",
    nome: "PostHog",
    categoria: "DevOps",
    icone: "BarChart3",
    descricao: "Product analytics, feature flags, session replay, A/B testing. Open source.",
    quandoUsar: "Production. Para entender como os utilizadores usam o site.",
    exemplo: "Vercel, Y Combinator startups.",
    url: "https://posthog.com",
    modoDefault: "alternativa",
  },
  {
    id: "github-actions",
    nome: "GitHub Actions CI/CD",
    categoria: "DevOps",
    icone: "GitBranch",
    descricao: "CI/CD pipelines. Lint, test, build, deploy automático em cada PR.",
    quandoUsar: "Production. Para garantir quality gates em cada merge.",
    exemplo: "Qualquer repo GitHub sério usa Actions.",
    url: "https://github.com/features/actions",
    modoDefault: "recomendada",
  },

  // ── Design ──
  {
    id: "figma-typography",
    nome: "Figma AI Typography",
    categoria: "Design",
    icone: "Type",
    descricao: "Plugin Figma que analisa hierarquia tipográfica e sugere pairings.",
    quandoUsar: "Durante a fase de Design System para validar tipografia.",
    exemplo: "Designers em agências premium usam para validar pairing.",
    url: "https://figma.com/community",
    modoDefault: "opcional",
  },
  {
    id: "figma-tokens",
    nome: "Figma Tokens Plugin",
    categoria: "Design",
    icone: "Palette",
    descricao: "Sync de design tokens entre Figma e código. CSS variables, Tailwind config.",
    quandoUsar: "Para manter tokens sincronizados entre design e dev.",
    exemplo: "Equipas que fazem design system sério.",
    url: "https://figma.com/community/plugin/843461159747178978",
    modoDefault: "alternativa",
  },
  {
    id: "chroma-js",
    nome: "chroma.js",
    categoria: "Design",
    icone: "Palette",
    descricao: "Biblioteca para manipulação de cores. WCAG contrast, scales, mixing.",
    quandoUsar: "Para gerar e validar paletas programaticamente.",
    exemplo: "Inaugura-Base usa chroma.js para validar WCAG AA.",
    url: "https://gka.github.io/chroma.js",
    modoDefault: "recomendada",
  },
  {
    id: "zod",
    nome: "Zod",
    categoria: "Design",
    icone: "ShieldCheck",
    descricao: "Schema validation type-safe. Para validar inputs, tool calling, configs.",
    quandoUsar: "SEMPRE para validar dados (server actions, API, tool calling).",
    exemplo: "Vercel, Linear, shadcn/ui form — todos usam Zod.",
    url: "https://zod.dev",
    modoDefault: "recomendada",
  },
  // NOVAS skills — mais cobertura
  {
    id: "tanstack-query",
    nome: "TanStack Query",
    categoria: "Backend",
    icone: "Database",
    descricao: "Data fetching + caching para React. Server state management.",
    quandoUsar: "Para apps com data fetching complexo (dashboards, admin panels).",
    exemplo: "Vercel dashboard, Linear, Cal.com admin.",
    url: "https://tanstack.com/query",
    modoDefault: "alternativa",
  },
  {
    id: "zustand",
    nome: "Zustand",
    categoria: "UI",
    icone: "Boxes",
    descricao: "State management minimalista. Simples, sem boilerplate.",
    quandoUsar: "Para client state complexo (carts, multi-step forms, dashboards).",
    exemplo: "Vercel, Linear, shadcn/ui examples.",
    url: "https://zustand-demo.pmnd.rs",
    modoDefault: "alternativa",
  },
  {
    id: "react-hook-form",
    nome: "React Hook Form",
    categoria: "UI",
    icone: "FormInput",
    descricao: "Forms performant para React. Validação com Zod, sem re-renders.",
    quandoUsar: "SEMPRE para forms (login, registro, checkout, settings).",
    exemplo: "Vercel, Linear, shadcn/ui form — todos usam RHF + Zod.",
    url: "https://react-hook-form.com",
    modoDefault: "recomendada",
  },
  {
    id: "lucide-react",
    nome: "Lucide Icons",
    categoria: "UI",
    icone: "Icon",
    descricao: "1000+ ícones open source. Tree-shakeable, consistentes.",
    quandoUsar: "SEMPRE. É o standard de ícones para shadcn/ui.",
    exemplo: "Vercel, Linear, shadcn/ui — todos usam Lucide.",
    url: "https://lucide.dev",
    modoDefault: "recomendada",
  },
  {
    id: "nuqs",
    nome: "Nuqs (URL state)",
    categoria: "UI",
    icone: "Link",
    descricao: "URL search params state management. Shareable, bookmarkable.",
    quandoUsar: "Para filtros, tabs, pagination que devem ser partilháveis via URL.",
    exemplo: "Vercel dashboard, Linear filters.",
    url: "https://nuqs.47ng.com",
    modoDefault: "opcional",
  },
  {
    id: "drizzle-orm",
    nome: "Drizzle ORM",
    categoria: "Backend",
    icone: "Database",
    descricao: "ORM type-safe leve. SQL-like API, edge-compatible.",
    quandoUsar: "Alternativa ao Prisma para edge/serverless (mais leve).",
    exemplo: "Vercel recommends Drizzle for edge.",
    url: "https://orm.drizzle.team",
    modoDefault: "alternativa",
  },
  {
    id: "turso",
    nome: "Turso (SQLite edge)",
    categoria: "Backend",
    icone: "Database",
    descricao: "SQLite distribuído na edge. Latência baixa global.",
    quandoUsar: "Para apps que precisam de DB na edge (baixa latência).",
    exemplo: "Vercel edge apps, Cloudflare Workers.",
    url: "https://turso.tech",
    modoDefault: "opcional",
  },
  {
    id: "inngest",
    nome: "Inngest",
    categoria: "Backend",
    icone: "Workflow",
    descricao: "Background jobs, queues, cron. Serverless-first.",
    quandoUsar: "Para jobs assíncronos (email, processing, webhooks).",
    exemplo: "Cal.com, Resend, Vercel apps.",
    url: "https://inngest.com",
    modoDefault: "opcional",
  },
  {
    id: "trigger-dev",
    nome: "Trigger.dev",
    categoria: "Backend",
    icone: "Workflow",
    descricao: "Background jobs type-safe. Alternative to Inngest.",
    quandoUsar: "Para jobs complexos com retries, schedules.",
    exemplo: "YC startups, indie hackers.",
    url: "https://trigger.dev",
    modoDefault: "opcional",
  },
  {
    id: "resend-react-email",
    nome: "React Email + Resend",
    categoria: "Backend",
    icone: "Mail",
    descricao: "Escreve emails com React. Preview, templates, DKIM.",
    quandoUsar: "Para emails transacionais (welcome, reset, receipts).",
    exemplo: "Vercel, Linear, Cal.com.",
    url: "https://react.email",
    modoDefault: "recomendada",
  },
  {
    id: "shadcn-table",
    nome: "shadcn/ui Table",
    categoria: "UI",
    icone: "Table",
    descricao: "Data table com sorting, filtering, pagination. Built on TanStack Table.",
    quandoUsar: "Para admin panels, dashboards, listas de dados.",
    exemplo: "Vercel, Linear admin, shadcn/ui examples.",
    url: "https://ui.shadcn.com/docs/components/data-table",
    modoDefault: "alternativa",
  },
  {
    id: "embla-carousel",
    nome: "Embla Carousel",
    categoria: "UI",
    icone: "Image",
    descricao: "Carousel lightweight e acessível. Usado pelo shadcn/ui.",
    quandoUsar: "Para carouséis, sliders, image galleries.",
    exemplo: "shadcn/ui carousel component.",
    url: "https://embla-carousel.vercel.app",
    modoDefault: "opcional",
  },
  {
    id: "vaul",
    nome: "Vaul (Drawer)",
    categoria: "UI",
    icone: "PanelBottom",
    descricao: "Drawer component para mobile. Bottom sheet animado.",
    quandoUsar: "Para filtros e navegação mobile (bottom sheet).",
    exemplo: "shadcn/ui drawer, iOS apps.",
    url: "https://vaul.emilkowal.dev",
    modoDefault: "opcional",
  },
  {
    id: "react-resizable-panels",
    nome: "Resizable Panels",
    categoria: "UI",
    icone: "Columns",
    descricao: "Painéis redimensionáveis. Split screen, IDE-like layouts.",
    quandoUsar: "Para IDEs, dashboards, editors com painéis.",
    exemplo: "Vercel dashboard, Linear, Figma-like UIs.",
    url: "https://react-resizable-panels.vercel.app",
    modoDefault: "opcional",
  },
  // ── NOVAS Skills (pesquisa Julho 2026 — top trending) ──────────────────
  {
    id: "once-ui",
    nome: "Once UI",
    categoria: "UI",
    icone: "Component",
    descricao: "Design system para Next.js. Componentes premium, animações incluídas, design system completo.",
    quandoUsar: "Para devs que querem design premium sem designer. Alternativa ao shadcn/ui com mais polish.",
    exemplo: "Trending no Reddit r/nextjs 2025, usado por startups.",
    url: "https://once-ui.com",
    modoDefault: "alternativa",
  },
  {
    id: "magic-ui",
    nome: "Magic UI",
    categoria: "UI",
    icone: "Wand2",
    descricao: "150+ componentes animados open source. Bento grids, sparkles, borders animadas.",
    quandoUsar: "Para componentes animados premium sem escrever animações do zero.",
    exemplo: "Trending no GitHub 2025, usado por agências e startups.",
    url: "https://magicui.design",
    modoDefault: "alternativa",
  },
  {
    id: "aceternity-ui",
    nome: "Aceternity UI",
    categoria: "UI",
    icone: "Sparkles",
    descricao: "Componentes free + paid. Efeitos 3D, parallax cards, background effects.",
    quandoUsar: "Para landing pages com efeitos visuais complexos (3D, parallax, glow).",
    exemplo: "Trending no Twitter/X 2025, awwwards-style components.",
    url: "https://ui.aceternity.com",
    modoDefault: "opcional",
  },
  {
    id: "tremor",
    nome: "Tremor",
    categoria: "UI",
    icone: "BarChart3",
    descricao: "Componentes de dashboard React. Charts, KPIs, tables, sparklines. Built on Recharts.",
    quandoUsar: "Para dashboards e admin panels com charts e métricas.",
    exemplo: "Vercel, Stripe dashboards usam componentes similares.",
    url: "https://tremor.so",
    modoDefault: "alternativa",
  },
  {
    id: "recharts",
    nome: "Recharts",
    categoria: "UI",
    icone: "BarChart3",
    descricao: "Charts React declarativos. Bar, line, pie, area, radar, compose. SVG-based.",
    quandoUsar: "Para qualquer chart em React. Standard da indústria.",
    exemplo: "Vercel analytics, Linear, Cal.com dashboards.",
    url: "https://recharts.org",
    modoDefault: "recomendada",
  },
  {
    id: "nivo",
    nome: "Nivo",
    categoria: "UI",
    icone: "BarChart3",
    descricao: "Data visualization React. 20+ chart types, server-side rendering, isomorphic.",
    quandoUsar: "Alternativa ao Recharts para charts mais complexos e customizáveis.",
    exemplo: "Data-heavy dashboards, analytics platforms.",
    url: "https://nivo.rocks",
    modoDefault: "opcional",
  },
  {
    id: "tanstack-table",
    nome: "TanStack Table",
    categoria: "UI",
    icone: "Table",
    descricao: "Headless table v8. Sorting, filtering, pagination, grouping, virtual rows.",
    quandoUsar: "Para data tables complexos. Base do shadcn/ui Table.",
    exemplo: "shadcn/ui Table, Vercel, Linear admin.",
    url: "https://tanstack.com/table",
    modoDefault: "recomendada",
  },
  {
    id: "dnd-kit",
    nome: "dnd-kit",
    categoria: "UI",
    icone: "Move",
    descricao: "Drag and drop React. Accessible, performant, headless. Kanban, sortable lists.",
    quandoUsar: "Para drag-drop (Kanban boards, sortable lists, file uploads).",
    exemplo: "Linear, Notion, Trello-like boards.",
    url: "https://dndkit.com",
    modoDefault: "opcional",
  },
  {
    id: "react-day-picker",
    nome: "React Day Picker",
    categoria: "UI",
    icone: "Calendar",
    descricao: "Date picker React. Accessible, localizado, range selection. Base do shadcn/ui.",
    quandoUsar: "Para date pickers e calendars em forms.",
    exemplo: "shadcn/ui Calendar, Cal.com, Booking apps.",
    url: "https://daypicker.dev",
    modoDefault: "recomendada",
  },
  {
    id: "react-dropzone",
    nome: "React Dropzone",
    categoria: "UI",
    icone: "Upload",
    descricao: "Drag-drop file uploads. HTML5 File API, thumbnails, validation.",
    quandoUsar: "Para upload de ficheiros com drag-drop.",
    exemplo: "UploadThing usa, Vercel, Notion attachments.",
    url: "https://react-dropzone.js.org",
    modoDefault: "opcional",
  },
  {
    id: "fullcalendar",
    nome: "FullCalendar",
    categoria: "UI",
    icone: "Calendar",
    descricao: "Calendar React completo. Month/week/day views, events, drag-drop, timezone.",
    quandoUsar: "Para apps com calendar complexo (booking, scheduling, CRM).",
    exemplo: "Cal.com, Google Calendar-like apps.",
    url: "https://fullcalendar.io",
    modoDefault: "opcional",
  },
  {
    id: "mantine",
    nome: "Mantine",
    categoria: "UI",
    icone: "Component",
    descricao: "Full React component library. 100+ components, hooks, forms. Alternativa ao MUI.",
    quandoUsar: "Alternativa ao shadcn/ui quando precisas de tudo pronto (sem copy-paste).",
    exemplo: "Usado por empresas que querem rapidez sem customizar.",
    url: "https://mantine.dev",
    modoDefault: "opcional",
  },
  {
    id: "mui",
    nome: "Material UI (MUI)",
    categoria: "UI",
    icone: "Component",
    descricao: "React component library Material Design. 50+ components, premium themes.",
    quandoUsar: "Para apps que seguem Material Design. Enterprise standard.",
    exemplo: "Google, JP Morgan, Bloomberg.",
    url: "https://mui.com",
    modoDefault: "opcional",
  },
  {
    id: "ant-design",
    nome: "Ant Design",
    categoria: "UI",
    icone: "Component",
    descricao: "Enterprise React UI. 60+ components, forms, tables, charts. Muito completo.",
    quandoUsar: "Para enterprise/admin panels complexos. Popular na Ásia.",
    exemplo: "Alibaba, Tencent, Blibli.",
    url: "https://ant.design",
    modoDefault: "opcional",
  },
  {
    id: "unistyles",
    nome: "Unistyles",
    categoria: "UI",
    icone: "Palette",
    descricao: "Universal styling para React Native + Web. Theme engine, runtime updates.",
    quandoUsar: "Para apps React Native + Web com styling unificado.",
    exemplo: "Trending GitHub 2025, React Native community.",
    url: "https://unistyl.es",
    modoDefault: "opcional",
  },
  {
    id: "tw-animate-css",
    nome: "tw-animate-css",
    categoria: "UI",
    icone: "Zap",
    descricao: "Animações CSS para Tailwind 4. Substitui tailwindcss-animate. Keyframes prontos.",
    quandoUsar: "SEMPRE com Tailwind 4. Animações CSS sem JS.",
    exemplo: "shadcn/ui New York usa tw-animate-css.",
    url: "https://github.com/romboHQ/tw-animate-css",
    modoDefault: "recomendada",
  },
  {
    id: "nuqs",
    nome: "Nuqs",
    categoria: "UI",
    icone: "Link",
    descricao: "URL search params state. Shareable, bookmarkable, type-safe.",
    quandoUsar: "Para filtros, tabs, pagination partilháveis via URL.",
    exemplo: "Vercel dashboard filters, Linear.",
    url: "https://nuqs.47ng.com",
    modoDefault: "opcional",
  },
  {
    id: "millions-dev",
    nome: "Millions (transitions)",
    categoria: "Animações",
    icone: "Zap",
    descricao: "Page transitions para Next.js App Router. Animações entre rotas nativas.",
    quandoUsar: "Para page transitions suaves em Next.js (estilo iOS/nativo).",
    exemplo: "Trending 2025, usado por startups premium.",
    url: "https://millions.dev",
    modoDefault: "opcional",
  },
  {
    id: "rive-react",
    nome: "Rive React",
    categoria: "Animações",
    icone: "Sparkles",
    descricao: "Rive runtime para React. Animações vetoriais interativas com state machine.",
    quandoUsar: "Para micro-interactions orgânicas, loading states, onboarding.",
    exemplo: "Mailchimp, Cash App, Slack.",
    url: "https://rive.app",
    modoDefault: "opcional",
  },
  {
    id: "valtio",
    nome: "Valtio",
    categoria: "UI",
    icone: "Boxes",
    descricao: "State management proxy-based. Simples, mutable API, reativo.",
    quandoUsar: "Alternativa ao Zustand para state simples e reativo.",
    exemplo: "PMNDROS ecosystem, usado com R3F.",
    url: "https://valtio.pmnd.rs",
    modoDefault: "opcional",
  },
  {
    id: "jotai",
    nome: "Jotai",
    categoria: "UI",
    icone: "Boxes",
    descricao: "Atomic state management. Bottom-up, granular, performant.",
    quandoUsar: "Para state complexo com dependências atómicas.",
    exemplo: "PMNDROS ecosystem, used with R3F and complex UIs.",
    url: "https://jotai.org",
    modoDefault: "opcional",
  },
  {
    id: "immer",
    nome: "Immer",
    categoria: "UI",
    icone: "Boxes",
    descricao: "Immutable state com sintaxe mutable. Simplifica reducers e state updates.",
    quandoUsar: "Com Redux ou useReducer para simplificar updates imutáveis.",
    exemplo: "Redux Toolkit usa Immer internamente.",
    url: "https://immerjs.github.io/immer",
    modoDefault: "opcional",
  },
  {
    id: "react-aria",
    nome: "React Aria",
    categoria: "UI",
    icone: "Accessibility",
    descricao: "Hooks acessíveis headless. Adobe. Date, select, tree, grid. WCAG completo.",
    quandoUsar: "Para componentes customizados que precisam de acessibilidade total.",
    exemplo: "Adobe Spectrum, React Aria Components.",
    url: "https://react-spectrum.adobe.com/react-aria",
    modoDefault: "alternativa",
  },
  {
    id: "downshift",
    nome: "Downshift",
    categoria: "UI",
    icone: "ChevronDown",
    descricao: "Autocomplete, combobox, select headless. Acessível, testável.",
    quandoUsar: "Para autocomplete e combobox customizados acessíveis.",
    exemplo: "Used by Uber, Atlassian, Netflix.",
    url: "https://downshift-js.com",
    modoDefault: "opcional",
  },
  {
    id: "react-window",
    nome: "React Window",
    categoria: "UI",
    icone: "List",
    descricao: "Virtual scrolling para listas grandes. Performance com 10k+ items.",
    quandoUsar: "Para listas/tabelas com muitos items (1000+).",
    exemplo: "Vercel logs, Spotify-like lists.",
    url: "https://github.com/bvaughn/react-window",
    modoDefault: "opcional",
  },
  {
    id: "react-hook-form-resolvers",
    nome: "RHF + Zod Resolvers",
    categoria: "UI",
    icone: "ShieldCheck",
    descricao: "Integração React Hook Form + Zod. Validação type-safe sem boilerplate.",
    quandoUsar: "SEMPRE com RHF + Zod. É o bridge entre os dois.",
    exemplo: "shadcn/ui Form, Vercel forms, Linear settings.",
    url: "https://github.com/react-hook-form/resolvers",
    modoDefault: "recomendada",
  },
  {
    id: " bcryptjs",
    nome: "bcryptjs",
    categoria: "Backend",
    icone: "Lock",
    descricao: "Password hashing. Pure JS, sem native bindings. Para Auth.js.",
    quandoUsar: "Sempre que tens passwords (registro, reset).",
    exemplo: "Auth.js recomenda bcryptjs.",
    url: "https://github.com/dcodeIO/bcrypt.js",
    modoDefault: "recomendada",
  },
  {
    id: "next-safe-action",
    nome: "next-safe-action",
    categoria: "Backend",
    icone: "ShieldCheck",
    descricao: "Type-safe Server Actions para Next.js. Validation, auth, error handling.",
    quandoUsar: "Para Server Actions production-grade com validação e auth.",
    exemplo: "Trending GitHub 2025, usado por Vercel apps.",
    url: "https://next-safe-action.dev",
    modoDefault: "alternativa",
  },
  {
    id: "drizzle-zod",
    nome: "Drizzle + Zod",
    categoria: "Backend",
    icone: "Database",
    descricao: "Schema Drizzle → Zod schemas automaticamente. Type-safe end-to-end.",
    quandoUsar: "Com Drizzle ORM para gerar validators Zod do schema.",
    exemplo: "Vercel recommends Drizzle + Zod for edge.",
    url: "https://orm.drizzle.team/docs/zod",
    modoDefault: "alternativa",
  },
  {
    id: "prisma-zod",
    nome: "Prisma + Zod",
    categoria: "Backend",
    icone: "Database",
    descricao: "Gera Zod schemas do Prisma schema. Type-safe DB → API → forms.",
    quandoUsar: "Com Prisma para validar inputs com base no schema.",
    exemplo: "Cal.com, Vercel apps com Prisma.",
    url: "https://github.com/CodedogLit/Prisma-zod-generator",
    modoDefault: "alternativa",
  },
  {
    id: "better-auth",
    nome: "Better Auth",
    categoria: "Backend",
    icone: "Lock",
    descricao: "Auth framework para Next.js. Sessions, OAuth, 2FA, organizations. Open source.",
    quandoUsar: "Alternativa ao Auth.js quando precisas de mais features (2FA, orgs).",
    exemplo: "Trending 2025, GitHub stars a crescer.",
    url: "https://better-auth.com",
    modoDefault: "alternativa",
  },
  {
    id: "clerk-next",
    nome: "Clerk (Next.js)",
    categoria: "Backend",
    icone: "Lock",
    descricao: "Auth-as-a-service com UI components. Social, orgs, MFA. Drop-in.",
    quandoUsar: "Para MVPs rápidos com auth completo sem configurar.",
    exemplo: "Replit, Vercel apps, YC startups.",
    url: "https://clerk.com/nextjs",
    modoDefault: "alternativa",
  },
  {
    id: "stripe-webhooks",
    nome: "Stripe Webhooks (Next.js)",
    categoria: "Backend",
    icone: "CreditCard",
    descricao: "Stripe webhook handler para Next.js. Signature verification, event routing.",
    quandoUsar: "Sempre que usas Stripe e precisas de webhooks.",
    exemplo: "Vercel Stripe starter, Cal.com.",
    url: "https://stripe.com/docs/webhooks",
    modoDefault: "recomendada",
  },
  {
    id: "react-email-render",
    nome: "React Email (render)",
    categoria: "Backend",
    icone: "Mail",
    descricao: "Renderiza React components para HTML email. Compatible com qualquer provider.",
    quandoUsar: "Para templates de email com React. Preview no browser.",
    exemplo: "Resend, Vercel, Linear.",
    url: "https://react.email",
    modoDefault: "recomendada",
  },
  {
    id: "ai-sdk-tools",
    nome: "Vercel AI SDK (tools)",
    categoria: "IA",
    icone: "Brain",
    descricao: "Tool calling, streaming, structured output. Multi-provider. Next.js native.",
    quandoUsar: "Para features de IA (chat, tool calling, RAG, structured output).",
    exemplo: "Vercel AI Chat, Perplexity-like apps, chatbot.co.",
    url: "https://sdk.vercel.ai",
    modoDefault: "recomendada",
  },
  {
    id: "langchain-js",
    nome: "LangChain.js",
    categoria: "IA",
    icone: "Brain",
    descricao: "Framework para LLM apps. Chains, agents, RAG, memory, tools.",
    quandoUsar: "Para apps de IA complexas (RAG, agents, multi-step reasoning).",
    exemplo: "Used by enterprise AI apps, Notion AI, ChatPDF.",
    url: "https://js.langchain.com",
    modoDefault: "opcional",
  },
  {
    id: "ai-sdk-rag",
    nome: "Vercel AI SDK (RAG)",
    categoria: "IA",
    icone: "Brain",
    descricao: "RAG pattern com Vercel AI SDK. Embeddings, vector search, streaming.",
    quandoUsar: "Para chatbots com knowledge base (docs, FAQ, products).",
    exemplo: "Vercel AI Chatbot template, Notion AI.",
    url: "https://sdk.vercel.ai/docs/rag",
    modoDefault: "opcional",
  },
  {
    id: "openai-realtime",
    nome: "OpenAI Realtime API",
    categoria: "IA",
    icone: "Radio",
    descricao: "WebSocket streaming para voice/chat em tempo real. Latência ultra-baixa.",
    quandoUsar: "Para voice assistants e chat em tempo real.",
    exemplo: "ChatGPT voice mode, customer support AI.",
    url: "https://platform.openai.com/docs/guides/realtime",
    modoDefault: "opcional",
  },
  {
    id: "pinecone",
    nome: "Pinecone",
    categoria: "IA",
    icone: "Database",
    descricao: "Vector database para RAG e semantic search. Serverless, escalável.",
    quandoUsar: "Para RAG com grande volume de documentos ou semantic search.",
    exemplo: "Microsoft, Notion AI, many AI startups.",
    url: "https://pinecone.io",
    modoDefault: "opcional",
  },
  {
    id: "vercel-kv",
    nome: "Vercel KV (Redis)",
    categoria: "Backend",
    icone: "Database",
    descricao: "Redis serverless na Vercel. Caching, sessions, rate limiting. Free tier.",
    quandoUsar: "Para caching e rate limiting em apps Vercel.",
    exemplo: "Vercel apps, Next.js rate limiting.",
    url: "https://vercel.com/kv",
    modoDefault: "alternativa",
  },
  {
    id: "vercel-blob",
    nome: "Vercel Blob",
    categoria: "Backend",
    icone: "Upload",
    descricao: "File storage serverless. Upload, serve, CDN. Integra com Next.js.",
    quandoUsar: "Para upload de imagens/ficheiros em apps Vercel.",
    exemplo: "Vercel apps, alternativa ao S3 para pequenos projetos.",
    url: "https://vercel.com/blob",
    modoDefault: "alternativa",
  },
  {
    id: "vercel-edge-config",
    nome: "Vercel Edge Config",
    categoria: "Backend",
    icone: "Zap",
    descricao: "Key-value store global na edge. Feature flags, config, A/B testing.",
    quandoUsar: "Para feature flags e config distribuída na edge.",
    exemplo: "Vercel, usado para Edge A/B testing.",
    url: "https://vercel.com/edge-config",
    modoDefault: "opcional",
  },
  {
    id: "react-scan",
    nome: "React Scan",
    categoria: "DevOps",
    icone: "Eye",
    descricao: "Detecta re-renders em tempo real. Performance debugging visual.",
    quandoUsar: "Para otimizar performance de React. Identifica componentes lentos.",
    exemplo: "Trending GitHub 2025, by million.js creator.",
    url: "https://github.com/aidenybai/react-scan",
    modoDefault: "opcional",
  },
  {
    id: "playwright",
    nome: "Playwright",
    categoria: "DevOps",
    icone: "Globe",
    descricao: "E2E testing cross-browser. Chromium, Firefox, WebKit. Screenshot, video.",
    quandoUsar: "Para E2E tests automatizados. Standard da indústria.",
    exemplo: "Vercel, Microsoft, Google usam Playwright.",
    url: "https://playwright.dev",
    modoDefault: "recomendada",
  },
  {
    id: "vitest",
    nome: "Vitest",
    categoria: "DevOps",
    icone: "Check",
    descricao: "Unit testing framework. Vite-native, fast, Jest-compatible API.",
    quandoUsar: "SEMPRE para unit tests. Substitui Jest em projetos Vite/Next.js.",
    exemplo: "Vercel, Linear, shadcn/ui — todos usam Vitest.",
    url: "https://vitest.dev",
    modoDefault: "recomendada",
  },
  {
    id: "biome",
    nome: "Biome",
    categoria: "DevOps",
    icone: "Zap",
    descricao: "Linter + formatter em Rust. Substitui ESLint + Prettier. Ultra-rápido.",
    quandoUsar: "Para linting/formatting rápido. Alternativa ao ESLint+Prettier.",
    exemplo: "Trending 2025, growing GitHub stars.",
    url: "https://biomejs.dev",
    modoDefault: "opcional",
  },
  {
    id: "turbopack",
    nome: "Turbopack",
    categoria: "DevOps",
    icone: "Zap",
    descricao: "Bundler Rust para Next.js. Substitui Webpack. 10x mais rápido em dev.",
    quandoUsar: "SEMPRE com Next.js 16. É o bundler nativo.",
    exemplo: "Vercel, Next.js 16 usa Turbopack por defeito.",
    url: "https://turbo.build/pack",
    modoDefault: "recomendada",
  },
  {
    id: "figma-ai-typography",
    nome: "Figma AI Typography",
    categoria: "Design",
    icone: "Type",
    descricao: "Plugin Figma AI para análise de hierarquia tipográfica e pairing suggestions.",
    quandoUsar: "Durante Design System para validar tipografia.",
    exemplo: "Designers em agências premium.",
    url: "https://figma.com/community",
    modoDefault: "opcional",
  },
  {
    id: "figma-tokens-plugin",
    nome: "Figma Tokens Plugin",
    categoria: "Design",
    icone: "Palette",
    descricao: "Sync design tokens entre Figma e código. CSS vars, Tailwind, Style Dictionary.",
    quandoUsar: "Para manter tokens sincronizados entre design e dev.",
    exemplo: "Equipas com design system sério.",
    url: "https://tokens.studio",
    modoDefault: "alternativa",
  },
  {
    id: "figma-anima",
    nome: "Anima (Figma → Code)",
    categoria: "Design",
    icone: "Code2",
    descricao: "Figma → React/Next.js code. Auto-layout detection, component mapping.",
    quandoUsar: "Para converter Figma designs em código React.",
    exemplo: "Agências, equipas que designam no Figma primeiro.",
    url: "https://animaapp.com",
    modoDefault: "opcional",
  },
  {
    id: "figma-builder-io",
    nome: "Builder.io (Figma → Code)",
    categoria: "Design",
    icone: "Code2",
    descricao: "Visual builder + Figma to code. AI-powered, Next.js optimized.",
    quandoUsar: "Para converter Figma em código production-ready.",
    exemplo: "Vercel, Hugo, large e-commerce.",
    url: "https://builder.io",
    modoDefault: "opcional",
  },
  {
    id: "style-dictionary",
    nome: "Style Dictionary",
    categoria: "Design",
    icone: "Palette",
    descricao: "Build system para design tokens. Transforma tokens em CSS, iOS, Android, etc.",
    quandoUsar: "Para multi-platform design tokens (web + mobile + desktop).",
    exemplo: "Amazon, Adobe, used by large design systems.",
    url: "https://styledictionary.com",
    modoDefault: "opcional",
  },
];

// ============================================================================
// INTEGRAÇÕES — catálogo separado
// ============================================================================
export interface Integracao {
  id: string;
  nome: string;
  categoria: "Pagamentos" | "Email" | "Analytics" | "Auth" | "Storage" | "Search" | "Comunicação" | "CMS" | "Cloud" | "Monitoring" | "Marketing" | "Maps" | "Outro";
  icone: string;
  descricao: string;
  quandoUsar: string;
  exemplo: string;
  url?: string;
  modoDefault: SkillMode;
}

export const INTEGRACOES_CATALOG: Integracao[] = [
  // Pagamentos
  { id: "stripe", nome: "Stripe", categoria: "Pagamentos", icone: "CreditCard", descricao: "Pagamentos online. Subscriptions, one-time, marketplace, billing.", quandoUsar: "Para qualquer e-commerce ou SaaS com pagamentos.", exemplo: "Vercel, Linear, Notion — todos usam Stripe.", url: "https://stripe.com", modoDefault: "recomendada" },
  { id: "paypal", nome: "PayPal", categoria: "Pagamentos", icone: "CreditCard", descricao: "Alternative payment method. Popular em US/EU.", quandoUsar: "Como alternativa ao Stripe ou em mercados onde PayPal domina.", exemplo: "Etsy, eBay, freelancers.", url: "https://paypal.com", modoDefault: "opcional" },
  { id: "mbway", nome: "MB WAY", categoria: "Pagamentos", icone: "CreditCard", descricao: "Pagamentos via telemóvel. Popular em Portugal.", quandoUsar: "Para e-commerce em Portugal.", exemplo: "Lojas portuguesas, Continente, Worten.", modoDefault: "opcional" },
  { id: "lemon-squeezy", nome: "Lemon Squeezy", categoria: "Pagamentos", icone: "CreditCard", descricao: "Merchant of record para SaaS. Handles VAT/tax globalmente.", quandoUsar: "Para SaaS que vende globalmente sem lidar com tax.", exemplo: "Indie hackers, SaaS solo founders.", url: "https://lemonsqueezy.com", modoDefault: "alternativa" },

  // Email
  { id: "resend", nome: "Resend", categoria: "Email", icone: "Mail", descricao: "Email API para developers. React Email, DKIM, tracking.", quandoUsar: "Para enviar emails transacionais (welcome, reset, receipts).", exemplo: "Vercel, Linear, Cal.com — todos usam Resend.", url: "https://resend.com", modoDefault: "recomendada" },
  { id: "sendgrid", nome: "SendGrid", categoria: "Email", icone: "Mail", descricao: "Email delivery platform. Marketing + transactional.", quandoUsar: "Para volume alto de emails ou marketing campaigns.", exemplo: "Spotify, Airbnb, Uber.", url: "https://sendgrid.com", modoDefault: "alternativa" },
  { id: "react-email", nome: "React Email", categoria: "Email", icone: "Mail", descricao: "Escreve emails com React components. Preview, templates.", quandoUsar: "Sempre que usas Resend ou similar para templates.", exemplo: "Resend, Vercel, Linear.", url: "https://react.email", modoDefault: "recomendada" },

  // Analytics
  { id: "google-analytics", nome: "Google Analytics 4", categoria: "Analytics", icone: "BarChart3", descricao: "Web analytics standard. Eventos, conversões, audiências.", quandoUsar: "Para tracking básico de tráfego (standard da indústria).", exemplo: "Quase todo site usa GA4.", url: "https://analytics.google.com", modoDefault: "recomendada" },
  { id: "plausible", nome: "Plausible", categoria: "Analytics", icone: "BarChart3", descricao: "Analytics privacy-friendly, sem cookies. GDPR compliant.", quandoUsar: "Para analytics privacy-first (GDPR, sem cookies).", exemplo: "Vercel docs, Laravel, Bun.", url: "https://plausible.io", modoDefault: "alternativa" },
  { id: "mixpanel", nome: "Mixpanel", categoria: "Analytics", icone: "BarChart3", descricao: "Product analytics profundo. Funnels, retention, cohorts.", quandoUsar: "Para SaaS que precisa de product analytics detalhado.", exemplo: "Uber, Airbnb, OpenAI.", url: "https://mixpanel.com", modoDefault: "opcional" },

  // Auth
  { id: "clerk", nome: "Clerk", categoria: "Auth", icone: "Lock", descricao: "Auth-as-a-service. UI components prontos, social login, orgs.", quandoUsar: "Alternativa ao NextAuth quando queres UI pronto e rápido.", exemplo: "Replit, Vercel apps, YC startups.", url: "https://clerk.com", modoDefault: "alternativa" },
  { id: "auth0", nome: "Auth0", categoria: "Auth", icone: "Lock", descricao: "Enterprise auth. SSO, SAML, MFA, compliance.", quandoUsar: "Para enterprise/B2B que precisa de SSO/SAML.", exemplo: "Atlassian, Slack enterprise.", url: "https://auth0.com", modoDefault: "opcional" },

  // Storage
  { id: "uploadthing", nome: "UploadThing", categoria: "Storage", icone: "Upload", descricao: "File uploads para Next.js. Type-safe, sem backend.", quandoUsar: "Para upload de imagens/ficheiros em Next.js.", exemplo: "Vercel apps, indie hackers.", url: "https://uploadthing.com", modoDefault: "recomendada" },
  { id: "cloudinary", nome: "Cloudinary", categoria: "Storage", icone: "Image", descricao: "Image/video CDN com transformações on-the-fly.", quandoUsar: "Para manipulação de imagens (resize, format, optimize).", exemplo: "Etsy, News sites, e-commerce.", url: "https://cloudinary.com", modoDefault: "alternativa" },

  // Search
  { id: "algolia", nome: "Algolia", categoria: "Search", icone: "Search", descricao: "Search-as-a-service. Instant search, typo tolerance, faceting.", quandoUsar: "Para e-commerce ou sites com muito conteúdo pesquisável.", exemplo: "Stripe docs, Notion, Loom.", url: "https://algolia.com", modoDefault: "alternativa" },
  { id: "meilisearch", nome: "Meilisearch", categoria: "Search", icone: "Search", descricao: "Search open source. Self-hosted ou cloud. Rápido.", quandoUsar: "Alternativa self-hosted ao Algolia.", exemplo: "Indie hackers, open source projects.", url: "https://meilisearch.com", modoDefault: "opcional" },

  // Comunicação
  { id: "livechat", nome: "LiveChat / Intercom", categoria: "Comunicação", icone: "MessageCircle", descricao: "Chat ao vivo para suporte. Bots, tickets, helpdesk.", quandoUsar: "Para SaaS/e-commerce que precisa de suporte ao cliente.", exemplo: "SaaS B2B, e-commerce premium.", url: "https://intercom.com", modoDefault: "opcional" },
  { id: "pusher", nome: "Pusher / Ably", categoria: "Comunicação", icone: "Radio", descricao: "Realtime websockets. Chat, live updates, collaboration.", quandoUsar: "Para features realtime (chat, cursors, live data).", exemplo: "Figma, Linear, Google Docs.", url: "https://pusher.com", modoDefault: "opcional" },

  // ── CMS ──
  { id: "sanity", nome: "Sanity", categoria: "CMS", icone: "Database", descricao: "CMS headless com real-time editor. Structured content, GROQ.", quandoUsar: "Para blogs, portfolios, sites com conteúdo dinâmico.", exemplo: "Linear blog, Vercel, Figma Community.", url: "https://sanity.io", modoDefault: "recomendada" },
  { id: "contentful", nome: "Contentful", categoria: "CMS", icone: "Database", descricao: "CMS headless enterprise. Multi-language, workflows.", quandoUsar: "Para enterprise, grandes equipas de conteúdo.", exemplo: "Spotify, Nike, Shopify enterprise.", url: "https://contentful.com", modoDefault: "alternativa" },
  { id: "strapi", nome: "Strapi", categoria: "CMS", icone: "Database", descricao: "CMS headless open source. Self-hosted, REST + GraphQL.", quandoUsar: "Para self-hosted, controlo total, custo zero.", exemplo: "Indie hackers, open source projects.", url: "https://strapi.io", modoDefault: "alternativa" },
  { id: "payload-cms", nome: "Payload CMS", categoria: "CMS", icone: "Database", descricao: "CMS headless Node.js + MongoDB/Postgres. Type-safe.", quandoUsar: "Para Next.js com CMS integrado, type-safe.", exemplo: "Vercel recommends Payload.", url: "https://payloadcms.com", modoDefault: "alternativa" },
  { id: "builder-io", nome: "Builder.io", categoria: "CMS", icone: "Boxes", descricao: "Visual page builder + headless CMS. Drag-drop editing.", quandoUsar: "Para marketing teams que querem editar visualmente.", exemplo: "Vercel, Hugo, large e-commerce.", url: "https://builder.io", modoDefault: "opcional" },
  { id: "wordpress-headless", nome: "WordPress Headless", categoria: "CMS", icone: "Database", descricao: "WP REST API + Next.js frontend. Backend familiar.", quandoUsar: "Para equipas que já conhecem WordPress.", exemplo: "News sites, blogs grandes.", url: "https://wordpress.org", modoDefault: "opcional" },

  // ── Cloud ──
  { id: "cloudflare", nome: "Cloudflare", categoria: "Cloud", icone: "Cloud", descricao: "CDN + edge computing + DNS + security. R2 storage, Workers.", quandoUsar: "Para CDN, edge functions, DDoS protection.", exemplo: "Discord, 1Password, Shopify.", url: "https://cloudflare.com", modoDefault: "recomendada" },
  { id: "aws", nome: "AWS", categoria: "Cloud", icone: "Cloud", descricao: "Amazon Web Services. EC2, S3, Lambda, RDS, full stack.", quandoUsar: "Para enterprise, infra complexa, multi-service.", exemplo: "Netflix, Airbnb, Slack.", url: "https://aws.amazon.com", modoDefault: "alternativa" },
  { id: "gcp", nome: "Google Cloud", categoria: "Cloud", icone: "Cloud", descricao: "Google Cloud Platform. Compute, storage, AI/ML, BigQuery.", quandoUsar: "Para data-heavy, AI/ML, BigQuery analytics.", exemplo: "Spotify, PayPal, Twitter.", url: "https://cloud.google.com", modoDefault: "opcional" },
  { id: "fly-io", nome: "Fly.io", categoria: "Cloud", icone: "Cloud", descricao: "Deploy apps globalmente perto dos utilizadores. Edge-first.", quandoUsar: "Para apps que precisam de baixa latência global.", exemplo: "Indie hackers, Phoenix/Elixir apps.", url: "https://fly.io", modoDefault: "opcional" },
  { id: "railway", nome: "Railway", categoria: "Cloud", icone: "Train", descricao: "Deploy backend apps sem configuração. DB + app em 1 click.", quandoUsar: "Para MVPs rápidos, protótipos backend.", exemplo: "YC startups, indie hackers.", url: "https://railway.app", modoDefault: "opcional" },
  { id: "digitalocean", nome: "DigitalOcean", categoria: "Cloud", icone: "Cloud", descricao: "VPS simples e barato. Droplets, App Platform, Spaces.", quandoUsar: "Para self-hosted, orçamento apertado.", exemplo: "Indie hackers, small businesses.", url: "https://digitalocean.com", modoDefault: "opcional" },

  // ── Monitoring ──
  { id: "sentry-integration", nome: "Sentry (integration)", categoria: "Monitoring", icone: "AlertCircle", descricao: "Error tracking + performance monitoring. Session replay.", quandoUsar: "Production. Essencial para monitorar erros.", exemplo: "Vercel, Linear, Discord.", url: "https://sentry.io", modoDefault: "recomendada" },
  { id: "logrocket", nome: "LogRocket", categoria: "Monitoring", icone: "Eye", descricao: "Session replay + console logs. Vê o que o user vê.", quandoUsar: "Para debug de issues em produção com contexto visual.", exemplo: "SaaS B2B, e-commerce.", url: "https://logrocket.com", modoDefault: "alternativa" },
  { id: "datadog", nome: "Datadog", categoria: "Monitoring", icone: "BarChart3", descricao: "Full-stack monitoring. Logs, metrics, traces, APM.", quandoUsar: "Para enterprise, infra complexa.", exemplo: "Airbnb, Samsung, 23andMe.", url: "https://datadoghq.com", modoDefault: "opcional" },
  { id: "better-stack", nome: "Better Stack", categoria: "Monitoring", icone: "Bell", descricao: "Uptime monitoring + logging + status pages.", quandoUsar: "Para monitoring simples e status pages.", exemplo: "Indie hackers, small teams.", url: "https://betterstack.com", modoDefault: "alternativa" },

  // ── Marketing ──
  { id: "mailchimp", nome: "Mailchimp", categoria: "Marketing", icone: "Mail", descricao: "Email marketing + automation + landing pages.", quandoUsar: "Para newsletters, campaigns, marketing automation.", exemplo: "Small businesses, e-commerce.", url: "https://mailchimp.com", modoDefault: "alternativa" },
  { id: "convertkit", nome: "ConvertKit", categoria: "Marketing", icone: "Mail", descricao: "Email marketing para creators. Newsletters, courses.", quandoUsar: "Para creators, bloggers, course sellers.", exemplo: "Indie hackers, YouTubers.", url: "https://convertkit.com", modoDefault: "opcional" },
  { id: "hubspot", nome: "HubSpot", categoria: "Marketing", icone: "Briefcase", descricao: "CRM + marketing + sales + service. All-in-one.", quandoUsar: "Para SaaS B2B que precisa de CRM + marketing.", exemplo: "B2B SaaS, enterprise.", url: "https://hubspot.com", modoDefault: "opcional" },
  { id: "segment", nome: "Segment", categoria: "Marketing", icone: "Split", descricao: "Customer data platform. Um SDK → múltiplos destinos.", quandoUsar: "Para integrar múltiplos analytics/marketing tools.", exemplo: "Vercel, Linear, enterprise.", url: "https://segment.com", modoDefault: "opcional" },

  // ── Maps ──
  { id: "mapbox", nome: "Mapbox", categoria: "Maps", icone: "Map", descricao: "Maps customizáveis, geocoding, directions. Developer-first.", quandoUsar: "Para mapas interativos, delivery, real estate.", exemplo: "Strava, Snapchat, Shopify.", url: "https://mapbox.com", modoDefault: "recomendada" },
  { id: "google-maps", nome: "Google Maps API", categoria: "Maps", icone: "Map", descricao: "Maps, places, routes, street view. Standard da indústria.", quandoUsar: "Para maps, location search, directions.", exemplo: "Uber, Airbnb, food delivery.", url: "https://maps.google.com", modoDefault: "alternativa" },
  { id: "leaflet", nome: "Leaflet", categoria: "Maps", icone: "Map", descricao: "Maps open source, leve. Sem API key necessário.", quandoUsar: "Para maps simples, self-hosted, sem custo.", exemplo: "Open source projects, gov sites.", url: "https://leafletjs.com", modoDefault: "opcional" },

  // ── NOVAS Integrações (pesquisa Julho 2026) ────────────────────────────
  // CMS adicionais
  { id: "sanity-next", nome: "Sanity (Next.js)", categoria: "CMS", icone: "Database", descricao: "Sanity Studio integrado com Next.js. Real-time preview, GROQ.", quandoUsar: "Para blogs e conteúdo dinâmico com preview real-time.", exemplo: "Linear blog, Vercel blog.", url: "https://sanity.io/nextjs", modoDefault: "recomendada" },
  { id: "payload-next", nome: "Payload (Next.js)", categoria: "CMS", icone: "Database", descricao: "Payload 3.0 integrado nativamente com Next.js App Router. Local API.", quandoUsar: "Para Next.js com CMS sem external service. Type-safe.", exemplo: "Vercel recommends Payload.", url: "https://payloadcms.com", modoDefault: "alternativa" },
  { id: "prismic", nome: "Prismic", categoria: "CMS", icone: "Database", descricao: "Headless CMS com Slice Machine. Visual editor, type-safe.", quandoUsar: "Para marketing teams que querem editar conteúdo visualmente.", exemplo: "Netflix, Google, Slack.", url: "https://prismic.io", modoDefault: "alternativa" },
  { id: "hygraph", nome: "Hygraph", categoria: "CMS", icone: "Database", descricao: "Headless CMS GraphQL-first. Real-time, content federation.", quandoUsar: "Para projetos GraphQL, content federation.", exemplo: "Samsung, Dr Oetker.", url: "https://hygraph.com", modoDefault: "opcional" },
  { id: "storyblok", nome: "Storyblok", categoria: "CMS", icone: "Database", descricao: "Headless CMS com visual editor. Component-based, multi-language.", quandoUsar: "Para equipas que querem editor visual drag-drop.", exemplo: "Adidas, Marriott, Renault.", url: "https://storyblok.com", modoDefault: "alternativa" },
  { id: "directus", nome: "Directus", categoria: "CMS", icone: "Database", descricao: "Headless CMS + BaaS. SQL database wrapper. Self-hosted ou cloud.", quandoUsar: "Para self-hosted com SQL existente. Free open source.", exemplo: "Samsung, Honda, Raytheon.", url: "https://directus.io", modoDefault: "opcional" },

  // Cloud adicionais
  { id: "render", nome: "Render", categoria: "Cloud", icone: "Cloud", descricao: "Cloud platform. Web services, DBs, background workers. Free tier.", quandoUsar: "Alternativa ao Railway, mais estável. Free SSL + CDN.", exemplo: "Indie hackers, small businesses.", url: "https://render.com", modoDefault: "opcional" },
  { id: "hetzner", nome: "Hetzner Cloud", categoria: "Cloud", icone: "Cloud", descricao: "VPS barato e potente. Europeu, GDPR-friendly. Best price/performance.", quandoUsar: "Para self-hosted barato. Best value cloud 2025-2026.", exemplo: "Growing popularity 2025-2026, YouTube devs recommend.", url: "https://hetzner.com/cloud", modoDefault: "opcional" },
  { id: "coolify", nome: "Coolify", categoria: "Cloud", icone: "Server", descricao: "Self-hosted Heroku/Vercel alternative. Open source. Deploy any app.", quandoUsar: "Para self-hosted Vercel-like experience on your own VPS.", exemplo: "Trending GitHub 2025, open source Vercel alternative.", url: "https://coolify.io", modoDefault: "opcional" },
  { id: "docker", nome: "Docker", categoria: "Cloud", icone: "Box", descricao: "Container platform. Empacota app + deps. Standard de deployment.", quandoUsar: "Para deployment consistente. Essencial para qualquer backend.", exemplo: "Quase toda empresa usa Docker.", url: "https://docker.com", modoDefault: "recomendada" },

  // Monitoring adicionais
  { id: "axiom", nome: "Axiom", categoria: "Monitoring", icone: "BarChart3", descricao: "Log management + analytics. Serverless-friendly. Vercel integration.", quandoUsar: "Para logs em serverless (Vercel não tem logs persistentes).", exemplo: "Vercel recommends Axiom for logs.", url: "https://axiom.co", modoDefault: "alternativa" },
  { id: "checkly", nome: "Checkly", categoria: "Monitoring", icone: "Check", descricao: "Monitoring + E2E testing. Playwright-based checks, API monitoring.", quandoUsar: "Para monitoring ativo (testar se site funciona a cada minuto).", exemplo: "Vercel, GitHub, Stripe.", url: "https://checklyhq.com", modoDefault: "opcional" },

  // Marketing adicionais
  { id: "posthog-next", nome: "PostHog (Next.js)", categoria: "Marketing", icone: "BarChart3", descricao: "Product analytics + feature flags + session replay. Open source. Next.js SDK.", quandoUsar: "Para entender como users usam o site. All-in-one.", exemplo: "Vercel, Y Combinator startups.", url: "https://posthog.com/docs/nextjs", modoDefault: "recomendada" },
  { id: "koala", nome: "Koala", categoria: "Marketing", icone: "BarChart3", descricao: "Product analytics. Funnels, retention. Server-side tracking.", quandoUsar: "Alternativa ao PostHog para analytics server-side.", exemplo: "Notion, Loom, Vercel.", url: "https://getkoala.com", modoDefault: "opcional" },
  { id: "customerio", nome: "Customer.io", categoria: "Marketing", icone: "Mail", descricao: "Marketing automation. Email, SMS, push. Behavioral triggers.", quandoUsar: "Para marketing automation com triggers comportamentais.", exemplo: "Notion, BuzzFeed, Blank Street.", url: "https://customer.io", modoDefault: "opcional" },

  // Search adicionais
  { id: "elastic", nome: "Elasticsearch", categoria: "Search", icone: "Search", descricao: "Search engine potente. Full-text, analytics, logs. Self-hosted ou cloud.", quandoUsar: "Para search com grande volume ou analytics complexo.", exemplo: "Wikipedia, GitHub, Netflix.", url: "https://elastic.co", modoDefault: "opcional" },
  { id: "typesense", nome: "Typesense", categoria: "Search", icone: "Search", descricao: "Search engine open source. Typo-tolerant, fast. Alternativa ao Algolia.", quandoUsar: "Alternativa self-hosted ao Algolia. Mais barato.", exemplo: "Growing popularity 2025, open source.", url: "https://typesense.org", modoDefault: "opcional" },

  // Pagamentos adicionais
  { id: "paddle", nome: "Paddle", categoria: "Pagamentos", icone: "CreditCard", descricao: "Merchant of record para SaaS. Handles tax, VAT, compliance global.", quandoUsar: "Para SaaS que vende globalmente sem lidar com tax/VAT.", exemplo: "Notion, Evernote, Setapp.", url: "https://paddle.com", modoDefault: "alternativa" },
  { id: "mollie", nome: "Mollie", categoria: "Pagamentos", icone: "CreditCard", descricao: "Pagamentos europeus. iDEAL, Bancontact, SEPA. Popular na EU.", quandoUsar: "Para e-commerce na Europa (iDEAL, Bancontact, SEPA).", exemplo: "Popular nos Países Baixos, Bélgica, Alemanha.", url: "https://mollie.com", modoDefault: "opcional" },

  // Auth adicionais
  { id: "stytch", nome: "Stytch", categoria: "Auth", icone: "Lock", descricao: "Passwordless auth. Magic links, passkeys, WebAuthn. Developer-first.", quandoUsar: "Para auth passwordless moderno (passkeys, magic links).", exemplo: "Growing 2025, passwordless trend.", url: "https://stytch.com", modoDefault: "opcional" },
  { id: "workos", nome: "WorkOS", categoria: "Auth", icone: "Lock", descricao: "Auth for B2B SaaS. SSO, SAML, SCIM, directory sync. Enterprise-ready.", quandoUsar: "Para B2B SaaS que precisa de SSO/SAML enterprise.", exemplo: "Vercel, Loom, Perplexity use WorkOS.", url: "https://workos.com", modoDefault: "alternativa" },

  // Storage adicionais
  { id: "imagekit", nome: "ImageKit", categoria: "Storage", icone: "Image", descricao: "Image CDN com transformações real-time. Resize, format, optimize.", quandoUsar: "Alternativa ao Cloudinary. Real-time image optimization.", exemplo: "Flipkart, TechCrunch, 10MB.io.", url: "https://imagekit.io", modoDefault: "alternativa" },
  { id: "imgix", nome: "Imgix", categoria: "Storage", icone: "Image", descricao: "Image CDN + processing. Resize, crop, format, watermark.", quandoUsar: "Para manipulação de imagens em CDN. Premium.", exemplo: "Netflix, Spotify, Reddit.", url: "https://imgix.com", modoDefault: "opcional" },
];

// ============================================================================
// Helpers: recomendar skills por nicho
// ============================================================================
export function getSkillsForNicho(nicho: string): Skill[] {
  // Base: todas com modoDefault "recomendada" são incluídas
  const base = SKILLS_CATALOG.filter((s) => s.modoDefault === "recomendada");

  // Adicionais por nicho
  const adicionais: Record<string, string[]> = {
    "SaaS B2B": ["cmdk", "posthog"],
    "E-commerce Moda": ["cloudinary", "algolia"],
    "E-commerce Geral": ["stripe", "cloudinary", "algolia"],
    "FinTech": ["sentry", "posthog"],
    "HealthTech": ["sentry", "posthog"],
    "Gaming": ["react-three-fiber", "rive"],
    "Crypto / Web3": ["react-three-fiber"],
    "Agência Criativa": ["gsap", "react-three-fiber", "magic-mcp"],
    "Portfólio Pessoal": ["gsap"],
    "Blog / Media": ["algolia"],
  };

  const extraIds = adicionais[nicho] ?? [];
  const extras = SKILLS_CATALOG.filter((s) => extraIds.includes(s.id));

  return [...base, ...extras];
}

export function getIntegracoesForNicho(nicho: string): Integracao[] {
  const base = INTEGRACOES_CATALOG.filter((i) => i.modoDefault === "recomendada");

  const adicionais: Record<string, string[]> = {
    "SaaS B2B": ["clerk"],
    "E-commerce Moda": ["stripe", "cloudinary", "algolia"],
    "E-commerce Geral": ["stripe", "cloudinary"],
    "FinTech": ["stripe"],
  };

  const extraIds = adicionais[nicho] ?? [];
  const extras = INTEGRACOES_CATALOG.filter((i) => extraIds.includes(i.id));

  return [...base, ...extras];
}
