// ============================================================================
// skins.ts — Skins atualizados 2026
// ============================================================================
// 3 skins principais novos (Linear Dark, Neural, Cloud) + alguns clássicos.
// O logo da app muda de cor conforme o accent do skin ativo.
// ============================================================================

export interface SkinTokens {
  bg: string;
  card: string;
  text: string;
  muted: string;
  accent: string;
  accentForeground: string;
  border: string;
  radius: string;
  shadow: string;
  headingFont: string;
  bodyFont: string;
  bgPattern?: string;
}

export interface Skin {
  id: string;
  name: string;
  description: string;
  category: string;
  dark: SkinTokens;
  light: SkinTokens;
  // Smart default: preset de cor sugerido no formulário quando este skin está ativo
  suggestedColorPreset?: string;
}

export const SKINS: Skin[] = [
  // ── 1. Linear Dark — dark mode profissional obrigatório ──────────────────
  {
    id: "linear-dark",
    name: "Linear Dark",
    description: "Dark mode profissional, SaaS premium",
    category: "Dark",
    suggestedColorPreset: "modern-blue",
    dark: {
      bg: "#0A0A0B",
      card: "#18181B",
      text: "#FAFAFA",
      muted: "#A1A1AA",
      accent: "#5E6AD2",
      accentForeground: "#FFFFFF",
      border: "#27272A",
      radius: "8px",
      shadow: "0 4px 24px rgba(0, 0, 0, 0.4), 0 1px 4px rgba(0, 0, 0, 0.3)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
    light: {
      bg: "#FAFAFA",
      card: "#FFFFFF",
      text: "#09090B",
      muted: "#71717A",
      accent: "#5E6AD2",
      accentForeground: "#FFFFFF",
      border: "#E4E4E7",
      radius: "8px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 2. Neural — AI-native, perfeito para Inaugura-Base ───────────────────
  {
    id: "neural",
    name: "Neural",
    description: "AI-native, roxo elétrico + ciano",
    category: "Dark",
    suggestedColorPreset: "violet-ai",
    dark: {
      bg: "#08080C",
      card: "#131320",
      text: "#F4F4F8",
      muted: "#9494B0",
      accent: "#8B5CF6",
      accentForeground: "#FFFFFF",
      border: "#2A2A3D",
      radius: "10px",
      shadow: "0 4px 24px rgba(139, 92, 246, 0.15), 0 1px 4px rgba(0, 0, 0, 0.4)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 20% 20%, rgba(139, 92, 246, 0.08) 0%, transparent 50%), radial-gradient(circle at 80% 80%, rgba(34, 211, 238, 0.06) 0%, transparent 40%)",
    },
    light: {
      bg: "#F5F3FF",
      card: "#FFFFFF",
      text: "#1E1B2E",
      muted: "#6B6885",
      accent: "#7C3AED",
      accentForeground: "#FFFFFF",
      border: "#DDD6FE",
      radius: "10px",
      shadow: "0 2px 12px rgba(124, 58, 237, 0.08)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 3. Cloud — melhor light mode ─────────────────────────────────────────
  {
    id: "cloud",
    name: "Cloud",
    description: "Light mode limpo, arejado, WCAG-AA",
    category: "Light",
    suggestedColorPreset: "neutral-premium",
    dark: {
      bg: "#0F172A",
      card: "#1E293B",
      text: "#F1F5F9",
      muted: "#94A3B8",
      accent: "#4F46E5",
      accentForeground: "#FFFFFF",
      border: "#334155",
      radius: "8px",
      shadow: "0 4px 24px rgba(0, 0, 0, 0.3)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
    light: {
      bg: "#F8FAFC",
      card: "#FFFFFF",
      text: "#0F172A",
      muted: "#64748B",
      accent: "#4F46E5",
      accentForeground: "#FFFFFF",
      border: "#E2E8F0",
      radius: "8px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.05)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 4. Mono Ink — clássico minimalista ───────────────────────────────────
  {
    id: "mono-ink",
    name: "Mono Ink",
    description: "Pure ink on cream, literary calm",
    category: "Mono",
    suggestedColorPreset: "monochrome",
    dark: {
      bg: "#0A0A0A",
      card: "#141414",
      text: "#EDEDED",
      muted: "#808080",
      accent: "#E0E0E0",
      accentForeground: "#0A0A0A",
      border: "#2A2A2A",
      radius: "4px",
      shadow: "0 2px 8px rgba(0, 0, 0, 0.6)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
    light: {
      bg: "#FAF7F0",
      card: "#FFFFFF",
      text: "#0A0A0A",
      muted: "#808080",
      accent: "#0A0A0A",
      accentForeground: "#FAF7F0",
      border: "#D0CCC0",
      radius: "4px",
      shadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 5. Brutalist Ink — bruto e arrojado ──────────────────────────────────
  {
    id: "brutalist-ink",
    name: "Brutalist Ink",
    description: "Bold black borders, hard offset shadows",
    category: "Brutalist",
    suggestedColorPreset: "high-contrast",
    dark: {
      bg: "#0D0D0D",
      card: "#1A1A1A",
      text: "#00FF88",
      muted: "#666666",
      accent: "#00FF88",
      accentForeground: "#0D0D0D",
      border: "#00FF88",
      radius: "0px",
      shadow: "6px 6px 0 #00FF88",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
    },
    light: {
      bg: "#FFFFFF",
      card: "#FFFFFF",
      text: "#0D0D0D",
      muted: "#666666",
      accent: "#0D0D0D",
      accentForeground: "#FFFFFF",
      border: "#0D0D0D",
      radius: "0px",
      shadow: "6px 6px 0 #0D0D0D",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
    },
  },

  // ── 6. Editorial Serif — elegante, tipografia editorial ──────────────────
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    description: "Serif headings, warm palette, magazine feel",
    category: "Editorial",
    suggestedColorPreset: "warm-coral",
    dark: {
      bg: "#12100E",
      card: "#1C1916",
      text: "#F5EFE6",
      muted: "#8A8276",
      accent: "#C4856A",
      accentForeground: "#12100E",
      border: "#2D2925",
      radius: "2px",
      shadow: "0 4px 16px rgba(0, 0, 0, 0.5)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
    light: {
      bg: "#F9F6F0",
      card: "#FFFFFF",
      text: "#1A1715",
      muted: "#8A8276",
      accent: "#9C5D3F",
      accentForeground: "#FFFFFF",
      border: "#D9D3CA",
      radius: "2px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 7. Dark Cyber Purple — neon/tech futurista ───────────────────────────
  {
    id: "dark-cyber-purple",
    name: "Dark Cyber Purple",
    description: "Roxo neon futurista, atmosfera tech/gaming",
    category: "Dark",
    suggestedColorPreset: "violet-ai",
    dark: {
      bg: "#1C1C1E",
      card: "#252528",
      text: "#FFFFFF",
      muted: "#8E8E93",
      accent: "#BF5AF2",
      accentForeground: "#FFFFFF",
      border: "#38383C",
      radius: "10px",
      shadow: "0 4px 24px rgba(191, 90, 242, 0.2), 0 1px 4px rgba(0, 0, 0, 0.4)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 20% 20%, rgba(191, 90, 242, 0.06) 0%, transparent 50%), radial-gradient(circle at 80% 80%, rgba(157, 78, 221, 0.04) 0%, transparent 40%)",
    },
    light: {
      bg: "#F3F0F7",
      card: "#FFFFFF",
      text: "#1C1C1E",
      muted: "#8E8E93",
      accent: "#9D4EDD",
      accentForeground: "#FFFFFF",
      border: "#E5E0EB",
      radius: "10px",
      shadow: "0 2px 12px rgba(157, 78, 221, 0.08)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 8. Obsidian — escuro profundo + roxo/azul ─────────────────────────────
  {
    id: "obsidian",
    name: "Obsidian",
    description: "Escuro profundo, elegante e focado, roxo/azul",
    category: "Dark",
    suggestedColorPreset: "violet-ai",
    dark: {
      bg: "#0F0F12",
      card: "#16161B",
      text: "#E8E8ED",
      muted: "#7A7A8C",
      accent: "#8B5CF6",
      accentForeground: "#FFFFFF",
      border: "#22222A",
      radius: "6px",
      shadow: "0 4px 24px rgba(0, 0, 0, 0.6), 0 0 12px rgba(139, 92, 246, 0.05)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
    light: {
      bg: "#F7F7F8",
      card: "#FFFFFF",
      text: "#0F0F12",
      muted: "#7A7A8C",
      accent: "#7C3AED",
      accentForeground: "#FFFFFF",
      border: "#E2E2E6",
      radius: "6px",
      shadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 9. Raw Concrete — brutalist puro, cinzas frios + amarelo neon ────────
  {
    id: "raw-concrete",
    name: "Raw Concrete",
    description: "Brutalist puro, cinzas frios + amarelo neon",
    category: "Brutalist",
    suggestedColorPreset: "high-contrast",
    dark: {
      bg: "#1A1A1D",
      card: "#242428",
      text: "#E4E4E7",
      muted: "#71717A",
      accent: "#EAB308",
      accentForeground: "#1A1A1D",
      border: "#3F3F46",
      radius: "0px",
      shadow: "4px 4px 0 #EAB308",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
    },
    light: {
      bg: "#E4E4E7",
      card: "#FFFFFF",
      text: "#18181B",
      muted: "#71717A",
      accent: "#18181B",
      accentForeground: "#E4E4E7",
      border: "#18181B",
      radius: "0px",
      shadow: "4px 4px 0 #18181B",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
    },
  },

  // ── 10. Glassmorphism — vidro fosco moderno ──────────────────────────────
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    description: "Vidro fosco moderno, blur + accent suave",
    category: "Glass",
    suggestedColorPreset: "soft-pastel",
    dark: {
      bg: "#0A0A0F",
      card: "rgba(30, 30, 45, 0.6)",
      text: "#F0F0F5",
      muted: "#9494A8",
      accent: "#60A5FA",
      accentForeground: "#0A0A0F",
      border: "rgba(255, 255, 255, 0.08)",
      radius: "16px",
      shadow: "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.05)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 30% 20%, rgba(96, 165, 250, 0.08) 0%, transparent 50%), radial-gradient(circle at 70% 80%, rgba(167, 139, 250, 0.06) 0%, transparent 40%)",
    },
    light: {
      bg: "#F0F2F5",
      card: "rgba(255, 255, 255, 0.7)",
      text: "#1A1A2E",
      muted: "#6B6B80",
      accent: "#3B82F6",
      accentForeground: "#FFFFFF",
      border: "rgba(0, 0, 0, 0.06)",
      radius: "16px",
      shadow: "0 8px 32px rgba(0, 0, 0, 0.06), inset 0 1px 0 rgba(255, 255, 255, 0.4)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 11. Wine — luxo escuro, bordeaux + dourado ────────────────────────────
  {
    id: "wine",
    name: "Wine",
    description: "Luxo escuro, bordeaux + dourado suave + preto",
    category: "Luxury",
    suggestedColorPreset: "warm-coral",
    dark: {
      bg: "#1A0A0E",
      card: "#261218",
      text: "#F5E6E8",
      muted: "#8A6B70",
      accent: "#C9A961",
      accentForeground: "#1A0A0E",
      border: "#3A1E24",
      radius: "4px",
      shadow: "0 4px 24px rgba(201, 169, 97, 0.1), 0 1px 4px rgba(0, 0, 0, 0.5)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 30% 20%, rgba(201, 169, 97, 0.04) 0%, transparent 50%), radial-gradient(circle at 70% 80%, rgba(139, 26, 47, 0.06) 0%, transparent 40%)",
    },
    light: {
      bg: "#FAF5F0",
      card: "#FFFFFF",
      text: "#1A0A0E",
      muted: "#8A6B70",
      accent: "#8B1A2F",
      accentForeground: "#FFFFFF",
      border: "#E8D5D0",
      radius: "4px",
      shadow: "0 2px 12px rgba(139, 26, 47, 0.06)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 12. Awwwards Void — deep void black with electric cyan accent ─────────
  {
    id: "awwwards-void",
    name: "Awwwards Void",
    description: "Deep void + electric cyan — Awwwards SOTD style",
    category: "Dark",
    suggestedColorPreset: "electric-lavender",
    dark: {
      bg: "#050507",
      card: "#0D0D12",
      text: "#F0F0F5",
      muted: "#6B6B7B",
      accent: "#00E5FF",
      accentForeground: "#050507",
      border: "#1A1A24",
      radius: "12px",
      shadow: "0 0 40px rgba(0, 229, 255, 0.08), 0 4px 24px rgba(0, 0, 0, 0.6)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 50% 0%, rgba(0, 229, 255, 0.06) 0%, transparent 60%)",
    },
    light: {
      bg: "#F5F5F7",
      card: "#FFFFFF",
      text: "#050507",
      muted: "#6B6B7B",
      accent: "#00B8D4",
      accentForeground: "#FFFFFF",
      border: "#E0E0E8",
      radius: "12px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 13. Bureau Studio — warm dark with coral accent (Bureau Cool style) ───
  {
    id: "bureau-studio",
    name: "Bureau Studio",
    description: "Warm dark + coral — creative agency Awwwards",
    category: "Dark",
    suggestedColorPreset: "sunset-coral",
    dark: {
      bg: "#0E0B08",
      card: "#1A1510",
      text: "#F5EDE0",
      muted: "#8A7E6B",
      accent: "#FF6B4A",
      accentForeground: "#0E0B08",
      border: "#2A2218",
      radius: "4px",
      shadow: "0 4px 24px rgba(255, 107, 74, 0.08), 0 1px 4px rgba(0, 0, 0, 0.5)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 20% 80%, rgba(255, 107, 74, 0.05) 0%, transparent 40%)",
    },
    light: {
      bg: "#FAF6F0",
      card: "#FFFFFF",
      text: "#0E0B08",
      muted: "#8A7E6B",
      accent: "#E54B2C",
      accentForeground: "#FFFFFF",
      border: "#E8DDD0",
      radius: "4px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 14. Terminal Mono — developer terminal aesthetic (Cursor/Vercel edge) ─
  {
    id: "terminal-mono",
    name: "Terminal Mono",
    description: "Terminal aesthetic — dev tools premium (Cursor style)",
    category: "Dark",
    suggestedColorPreset: "terminal-green",
    dark: {
      bg: "#0A0E0A",
      card: "#111611",
      text: "#C8E6C9",
      muted: "#4A6B4E",
      accent: "#00FF88",
      accentForeground: "#0A0E0A",
      border: "#1A2218",
      radius: "2px",
      shadow: "0 0 20px rgba(0, 255, 136, 0.06), 0 2px 8px rgba(0, 0, 0, 0.5)",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
      bgPattern: "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0, 255, 136, 0.01) 2px, rgba(0, 255, 136, 0.01) 4px)",
    },
    light: {
      bg: "#F0F5F0",
      card: "#FFFFFF",
      text: "#0A1E0A",
      muted: "#4A6B4E",
      accent: "#00C853",
      accentForeground: "#FFFFFF",
      border: "#D0E0D0",
      radius: "2px",
      shadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
      headingFont: "var(--font-mono), ui-monospace, monospace",
      bodyFont: "var(--font-mono), ui-monospace, monospace",
    },
  },

  // ── 15. Aurora — gradient mesh dark (Stripe/Linear gradient hero) ─────────
  {
    id: "aurora",
    name: "Aurora",
    description: "Gradient mesh dark — aurora borealis premium",
    category: "Dark",
    suggestedColorPreset: "electric-lavender",
    dark: {
      bg: "#080812",
      card: "#0F0F1E",
      text: "#EDEDF5",
      muted: "#7878A0",
      accent: "#A78BFA",
      accentForeground: "#080812",
      border: "#1E1E32",
      radius: "16px",
      shadow: "0 0 60px rgba(167, 139, 250, 0.06), 0 4px 24px rgba(0, 0, 0, 0.5)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(ellipse at 20% 30%, rgba(167, 139, 250, 0.08) 0%, transparent 50%), radial-gradient(ellipse at 80% 70%, rgba(0, 229, 255, 0.06) 0%, transparent 50%), radial-gradient(ellipse at 50% 50%, rgba(236, 72, 153, 0.04) 0%, transparent 60%)",
    },
    light: {
      bg: "#FAFAFF",
      card: "#FFFFFF",
      text: "#080812",
      muted: "#7878A0",
      accent: "#7C3AED",
      accentForeground: "#FFFFFF",
      border: "#E8E8F0",
      radius: "16px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 16. Obsidian Gold — luxury dark with gold (Sotheby's style) ───────────
  {
    id: "obsidian-gold",
    name: "Obsidian Gold",
    description: "Luxury dark + gold accent — premium/luxury brands",
    category: "Dark",
    suggestedColorPreset: "obsidian-gold",
    dark: {
      bg: "#070705",
      card: "#0F0E08",
      text: "#F5F0E0",
      muted: "#7A7460",
      accent: "#C9A961",
      accentForeground: "#070705",
      border: "#1E1C10",
      radius: "2px",
      shadow: "0 0 30px rgba(201, 169, 97, 0.06), 0 2px 12px rgba(0, 0, 0, 0.6)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 50% 0%, rgba(201, 169, 97, 0.04) 0%, transparent 50%)",
    },
    light: {
      bg: "#FAF8F0",
      card: "#FFFFFF",
      text: "#070705",
      muted: "#7A7460",
      accent: "#B8956A",
      accentForeground: "#FFFFFF",
      border: "#E8E0D0",
      radius: "2px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.06)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 17. Void Cyan — void black + cyan (variação do Void, mais cyan glow) ──
  {
    id: "void-cyan",
    name: "Void Cyan",
    description: "Void + cyan glow intenso — Awwwards SOTD electric",
    category: "Dark",
    dark: {
      bg: "#040408",
      card: "#0A0A12",
      text: "#E8F4F8",
      muted: "#4A6B7B",
      accent: "#22D3EE",
      accentForeground: "#040408",
      border: "#12121E",
      radius: "10px",
      shadow: "0 0 50px rgba(34, 211, 238, 0.10), 0 4px 20px rgba(0, 0, 0, 0.6)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(ellipse at 50% 0%, rgba(34, 211, 238, 0.10) 0%, transparent 50%), radial-gradient(circle at 80% 80%, rgba(34, 211, 238, 0.03) 0%, transparent 30%)",
    },
    light: {
      bg: "#F0FAFC",
      card: "#FFFFFF",
      text: "#040408",
      muted: "#5A7B8B",
      accent: "#0891B2",
      accentForeground: "#FFFFFF",
      border: "#D0E8F0",
      radius: "10px",
      shadow: "0 2px 12px rgba(8, 145, 178, 0.08)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 18. Void Magenta — REMOVIDO (substituído por skins 10/10 melhores) ──

  // ── 19. Aurora Teal — aurora gradient mesh with teal/emerald ──────────────
  {
    id: "aurora-teal",
    name: "Aurora Teal",
    description: "Gradient mesh teal + emerald — aurora borealis green",
    category: "Dark",
    dark: {
      bg: "#040A08",
      card: "#0A1612",
      text: "#E0F5E8",
      muted: "#4A7B5B",
      accent: "#10B981",
      accentForeground: "#040A08",
      border: "#0E2018",
      radius: "16px",
      shadow: "0 0 60px rgba(16, 185, 129, 0.06), 0 4px 24px rgba(0, 0, 0, 0.5)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(ellipse at 20% 20%, rgba(16, 185, 129, 0.08) 0%, transparent 50%), radial-gradient(ellipse at 80% 60%, rgba(34, 211, 238, 0.06) 0%, transparent 50%), radial-gradient(ellipse at 50% 80%, rgba(132, 204, 22, 0.04) 0%, transparent 50%)",
    },
    light: {
      bg: "#F0FCF5",
      card: "#FFFFFF",
      text: "#040A08",
      muted: "#4A7B5B",
      accent: "#059669",
      accentForeground: "#FFFFFF",
      border: "#D0F0DC",
      radius: "16px",
      shadow: "0 2px 12px rgba(5, 150, 105, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 20. Obsidian Platinum — luxury dark + silver/platinum ─────────────────
  {
    id: "obsidian-platinum",
    name: "Obsidian Platinum",
    description: "Luxury dark + platinum silver — ultra premium",
    category: "Dark",
    dark: {
      bg: "#060608",
      card: "#0C0C10",
      text: "#E8E8F0",
      muted: "#686878",
      accent: "#B0B0C0",
      accentForeground: "#060608",
      border: "#18181E",
      radius: "2px",
      shadow: "0 0 30px rgba(176, 176, 192, 0.04), 0 2px 12px rgba(0, 0, 0, 0.6)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 50% 0%, rgba(176, 176, 192, 0.03) 0%, transparent 50%)",
    },
    light: {
      bg: "#F8F8FC",
      card: "#FFFFFF",
      text: "#060608",
      muted: "#686878",
      accent: "#6B7280",
      accentForeground: "#FFFFFF",
      border: "#E4E4EC",
      radius: "2px",
      shadow: "0 2px 12px rgba(0, 0, 0, 0.04)",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ── 21. Aurora Sunset — gradient mesh warm (orange/pink/purple) ───────────
  {
    id: "aurora-sunset",
    name: "Aurora Sunset",
    description: "Gradient mesh warm — sunset orange/pink/purple",
    category: "Dark",
    dark: {
      bg: "#0A0608",
      card: "#120A0E",
      text: "#F5E8EC",
      muted: "#7B5A60",
      accent: "#F97316",
      accentForeground: "#0A0608",
      border: "#1E1218",
      radius: "16px",
      shadow: "0 0 60px rgba(249, 115, 22, 0.06), 0 4px 24px rgba(0, 0, 0, 0.5)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(ellipse at 20% 30%, rgba(249, 115, 22, 0.08) 0%, transparent 50%), radial-gradient(ellipse at 80% 60%, rgba(236, 72, 153, 0.06) 0%, transparent 50%), radial-gradient(ellipse at 50% 80%, rgba(139, 92, 246, 0.04) 0%, transparent 50%)",
    },
    light: {
      bg: "#FFF8F5",
      card: "#FFFFFF",
      text: "#0A0608",
      muted: "#7B5A60",
      accent: "#EA580C",
      accentForeground: "#FFFFFF",
      border: "#FAE0D0",
      radius: "16px",
      shadow: "0 2px 12px rgba(234, 88, 12, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
    },
  },

  // ════════════════════════════════════════════════════════════════════════
  // 3 SKINS 10/10 — top tier premium (Nov 2026)
  // ════════════════════════════════════════════════════════════════════════

  // ── 22. Neon Delight — neons a brilhar (cyberpunk premium glow) ───────────
  {
    id: "neon-delight",
    name: "Neon Delight",
    description: "Neons a brilhar — cyberpunk premium com glow intenso",
    category: "Neon",
    suggestedColorPreset: "cyber-magenta",
    dark: {
      bg: "#050208",
      card: "#0E0614",
      text: "#F0E6FF",
      muted: "#7A5A9B",
      accent: "#FF00E5",
      accentForeground: "#050208",
      border: "rgba(255, 0, 229, 0.25)",
      radius: "12px",
      shadow: "0 0 40px rgba(255, 0, 229, 0.35), 0 0 80px rgba(0, 255, 200, 0.15), 0 4px 20px rgba(0, 0, 0, 0.8)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 20% 30%, rgba(255, 0, 229, 0.12) 0%, transparent 45%), radial-gradient(circle at 80% 20%, rgba(0, 255, 200, 0.10) 0%, transparent 40%), radial-gradient(circle at 50% 80%, rgba(124, 58, 237, 0.08) 0%, transparent 50%), radial-gradient(circle at 10% 90%, rgba(255, 235, 59, 0.05) 0%, transparent 35%)",
    },
    light: {
      bg: "#FFF5FF",
      card: "#FFFFFF",
      text: "#1A0512",
      muted: "#7A5A7B",
      accent: "#C026D3",
      accentForeground: "#FFFFFF",
      border: "rgba(192, 38, 211, 0.15)",
      radius: "12px",
      shadow: "0 0 24px rgba(192, 38, 211, 0.20), 0 4px 16px rgba(0, 0, 0, 0.06)",
      headingFont: "var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(circle at 20% 30%, rgba(192, 38, 211, 0.06) 0%, transparent 45%), radial-gradient(circle at 80% 70%, rgba(0, 200, 200, 0.04) 0%, transparent 40%)",
    },
  },

  // ── 23. Concrete Premium — Raw Concrete melhorado (brutalist moderno) ─────
  // Inspirado no Raw Concrete mas mais refinado: cinzas quentes + accent vibrante
  // + tipografia display moderna + sombras hard-edge premium
  {
    id: "concrete-premium",
    name: "Concrete Premium",
    description: "Brutalist moderno — cinzas quentes + accent vibrante + display",
    category: "Brutalist",
    suggestedColorPreset: "matrix-amber",
    dark: {
      bg: "#1C1B1A",
      card: "#262523",
      text: "#F5F2EE",
      muted: "#8A857E",
      accent: "#FF6B35",
      accentForeground: "#1C1B1A",
      border: "#3D3A36",
      radius: "2px",
      shadow: "6px 6px 0 #FF6B35, 0 0 0 1px #1C1B1A",
      headingFont: "var(--font-clash-display), var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "linear-gradient(135deg, rgba(255, 107, 53, 0.02) 0%, transparent 50%), radial-gradient(circle at 90% 10%, rgba(255, 107, 53, 0.04) 0%, transparent 30%)",
    },
    light: {
      bg: "#F5F2EE",
      card: "#FFFFFF",
      text: "#1C1B1A",
      muted: "#6B6660",
      accent: "#1C1B1A",
      accentForeground: "#FF6B35",
      border: "#1C1B1A",
      radius: "2px",
      shadow: "6px 6px 0 #1C1B1A, 0 0 0 1px #1C1B1A",
      headingFont: "var(--font-clash-display), var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "linear-gradient(135deg, rgba(28, 27, 26, 0.01) 0%, transparent 50%)",
    },
  },

  // ── 24. Aurora Mesh Pro — gradient mesh premium Awwwards 2026 ─────────────
  // Inspirado em Linear + Vercel + Stripe — mesh gradient violet/blue/cyan
  // com glow subtil, tipografia Geist, e profundidade atmosférica
  {
    id: "aurora-mesh-pro",
    name: "Aurora Mesh Pro",
    description: "Gradient mesh premium — Linear/Vercel/Stripe style atmosférico",
    category: "Premium",
    suggestedColorPreset: "electric-lavender",
    dark: {
      bg: "#08060F",
      card: "#100C1F",
      text: "#F0EDFA",
      muted: "#7A6F9B",
      accent: "#8B5CF6",
      accentForeground: "#08060F",
      border: "rgba(139, 92, 246, 0.18)",
      radius: "14px",
      shadow: "0 0 60px rgba(139, 92, 246, 0.12), 0 8px 32px rgba(0, 0, 0, 0.6)",
      headingFont: "var(--font-geist), var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(at 20% 20%, rgba(139, 92, 246, 0.15) 0px, transparent 50%), radial-gradient(at 80% 10%, rgba(59, 130, 246, 0.12) 0px, transparent 45%), radial-gradient(at 70% 80%, rgba(6, 182, 212, 0.10) 0px, transparent 50%), radial-gradient(at 10% 70%, rgba(236, 72, 153, 0.06) 0px, transparent 40%)",
    },
    light: {
      bg: "#FAF8FF",
      card: "#FFFFFF",
      text: "#1A0F2E",
      muted: "#6B5F8A",
      accent: "#7C3AED",
      accentForeground: "#FFFFFF",
      border: "rgba(124, 58, 237, 0.12)",
      radius: "14px",
      shadow: "0 4px 24px rgba(124, 58, 237, 0.08), 0 1px 3px rgba(0, 0, 0, 0.04)",
      headingFont: "var(--font-geist), var(--font-inter), system-ui, sans-serif",
      bodyFont: "var(--font-inter), system-ui, sans-serif",
      bgPattern: "radial-gradient(at 20% 20%, rgba(139, 92, 246, 0.06) 0px, transparent 50%), radial-gradient(at 80% 10%, rgba(59, 130, 246, 0.04) 0px, transparent 45%), radial-gradient(at 70% 80%, rgba(6, 182, 212, 0.03) 0px, transparent 50%)",
    },
  },
];

export function getSkinById(id: string): Skin | undefined {
  return SKINS.find((s) => s.id === id);
}
